// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

const getProviderEarningsHistory = `-- name: GetProviderEarningsHistory :many
SELECT
    DATE_TRUNC('month', t.paid_at) AS month,
    COALESCE(SUM(t.provider_payout_amount::numeric), 0)::float8 AS earnings,
    COUNT(*)::int AS job_count
FROM transactions t
JOIN jobs j ON j.id = t.job_id
WHERE j.provider_id = $1
  AND t.payment_status = 'captured'
  AND t.paid_at >= NOW() - ($2::int || ' months')::interval
GROUP BY DATE_TRUNC('month', t.paid_at)
ORDER BY month ASC
`

type GetProviderEarningsHistoryRow struct {
	Month    time.Time `json:"month"`
	Earnings float64   `json:"earnings"`
	JobCount int       `json:"job_count"`
}

func (q *Queries) GetProviderEarningsHistory(ctx context.Context, providerID uuid.UUID, months int) ([]GetProviderEarningsHistoryRow, error) {
	rows, err := q.db.Query(ctx, getProviderEarningsHistory, providerID, months)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get provider earnings history")
		return nil, err
	}
	defer rows.Close()

	var items []GetProviderEarningsHistoryRow
	for rows.Next() {
		var i GetProviderEarningsHistoryRow
		if err := rows.Scan(&i.Month, &i.Earnings, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDemandByCategory = `-- name: GetDemandByCategory :many
SELECT
    c.id AS category_id,
    c.slug AS category_slug,
    COALESCE((c.name->>'en')::text, c.slug) AS category_name,
    COUNT(j.id)::int AS demand_count
FROM jobs j
JOIN categories c ON c.id = j.category_id
WHERE j.status IN ('posted', 'quoted', 'accepted', 'in_progress', 'completed')
  AND j.location IS NOT NULL
  AND ST_DWithin(
      j.location::geography,
      ST_MakePoint($1, $2)::geography,
      $3
  )
  AND j.created_at >= NOW() - INTERVAL '90 days'
GROUP BY c.id, c.slug, c.name
ORDER BY demand_count DESC
`

type GetDemandByCategoryRow struct {
	CategoryID   uuid.UUID `json:"category_id"`
	CategorySlug string    `json:"category_slug"`
	CategoryName string    `json:"category_name"`
	DemandCount  int       `json:"demand_count"`
}

func (q *Queries) GetDemandByCategory(ctx context.Context, lng float64, lat float64, radiusMeters float64) ([]GetDemandByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getDemandByCategory, lng, lat, radiusMeters)
	if err != nil {
		log.Error().Err(err).Float64("lat", lat).Float64("lng", lng).Msg("failed to get demand by category")
		return nil, err
	}
	defer rows.Close()

	var items []GetDemandByCategoryRow
	for rows.Next() {
		var i GetDemandByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.CategorySlug, &i.CategoryName, &i.DemandCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDemandByPostcode = `-- name: GetDemandByPostcode :many
SELECT
    j.postcode::text AS postcode,
    COUNT(j.id)::int AS demand_count,
    AVG(ST_Y(j.location::geometry))::float8 AS lat,
    AVG(ST_X(j.location::geometry))::float8 AS lng
FROM jobs j
WHERE j.status IN ('posted', 'quoted', 'accepted', 'in_progress', 'completed')
  AND j.postcode IS NOT NULL
  AND j.location IS NOT NULL
  AND ST_DWithin(
      j.location::geography,
      ST_MakePoint($1, $2)::geography,
      $3
  )
  AND j.created_at >= NOW() - INTERVAL '90 days'
GROUP BY j.postcode
ORDER BY demand_count DESC
`

type GetDemandByPostcodeRow struct {
	Postcode    string  `json:"postcode"`
	DemandCount int     `json:"demand_count"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
}

func (q *Queries) GetDemandByPostcode(ctx context.Context, lng float64, lat float64, radiusMeters float64) ([]GetDemandByPostcodeRow, error) {
	rows, err := q.db.Query(ctx, getDemandByPostcode, lng, lat, radiusMeters)
	if err != nil {
		log.Error().Err(err).Float64("lat", lat).Float64("lng", lng).Msg("failed to get demand by postcode")
		return nil, err
	}
	defer rows.Close()

	var items []GetDemandByPostcodeRow
	for rows.Next() {
		var i GetDemandByPostcodeRow
		if err := rows.Scan(&i.Postcode, &i.DemandCount, &i.Lat, &i.Lng); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getProviderPerformanceMetrics = `-- name: GetProviderPerformanceMetrics :one
SELECT
    COALESCE(
        (SELECT COUNT(DISTINCT jq.job_id)::float8 / NULLIF(COUNT(DISTINCT j2.id), 0)
         FROM jobs j2
         LEFT JOIN job_quotes jq ON jq.job_id = j2.id AND jq.provider_id = $1
         WHERE j2.category_id IN (SELECT category_id FROM provider_categories WHERE provider_id = $1)
           AND j2.created_at >= NOW() - INTERVAL '90 days'
           AND j2.status != 'draft'),
        0
    )::float8 AS response_rate,
    COALESCE(
        (SELECT COUNT(*)::float8 FROM jobs WHERE provider_id = $1 AND status = 'completed' AND created_at >= NOW() - INTERVAL '90 days')
        / NULLIF(
            (SELECT COUNT(*)::float8 FROM jobs WHERE provider_id = $1 AND status IN ('accepted', 'in_progress', 'completed') AND created_at >= NOW() - INTERVAL '90 days'),
            0
        ),
        0
    )::float8 AS completion_rate,
    COALESCE(
        (SELECT AVG(r.rating)::float8 FROM reviews r WHERE r.reviewee_id = $1),
        0
    )::float8 AS avg_rating,
    (SELECT COUNT(*)::int FROM reviews r WHERE r.reviewee_id = $1) AS total_reviews,
    COALESCE(
        (SELECT SUM(t.provider_payout_amount::numeric)::float8
         FROM transactions t
         JOIN jobs j ON j.id = t.job_id
         WHERE j.provider_id = $1 AND t.payment_status = 'captured'),
        0
    )::float8 AS total_earnings
`

type GetProviderPerformanceMetricsRow struct {
	ResponseRate   float64 `json:"response_rate"`
	CompletionRate float64 `json:"completion_rate"`
	AvgRating      float64 `json:"avg_rating"`
	TotalReviews   int     `json:"total_reviews"`
	TotalEarnings  float64 `json:"total_earnings"`
}

func (q *Queries) GetProviderPerformanceMetrics(ctx context.Context, providerID uuid.UUID) (GetProviderPerformanceMetricsRow, error) {
	row := q.db.QueryRow(ctx, getProviderPerformanceMetrics, providerID)
	var i GetProviderPerformanceMetricsRow
	err := row.Scan(
		&i.ResponseRate,
		&i.CompletionRate,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalEarnings,
	)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get provider performance metrics")
	}
	return i, err
}

const getPeakDemandHours = `-- name: GetPeakDemandHours :many
SELECT
    EXTRACT(HOUR FROM j.created_at)::int AS hour_of_day,
    COUNT(j.id)::int AS demand_count
FROM jobs j
WHERE j.status IN ('posted', 'quoted', 'accepted', 'in_progress', 'completed')
  AND j.category_id IN (SELECT category_id FROM provider_categories WHERE provider_id = $1)
  AND j.created_at >= NOW() - INTERVAL '90 days'
GROUP BY EXTRACT(HOUR FROM j.created_at)
ORDER BY hour_of_day ASC
`

type GetPeakDemandHoursRow struct {
	HourOfDay   int `json:"hour_of_day"`
	DemandCount int `json:"demand_count"`
}

func (q *Queries) GetPeakDemandHours(ctx context.Context, providerID uuid.UUID) ([]GetPeakDemandHoursRow, error) {
	rows, err := q.db.Query(ctx, getPeakDemandHours, providerID)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get peak demand hours")
		return nil, err
	}
	defer rows.Close()

	var items []GetPeakDemandHoursRow
	for rows.Next() {
		var i GetPeakDemandHoursRow
		if err := rows.Scan(&i.HourOfDay, &i.DemandCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getCompetitorDensity = `-- name: GetCompetitorDensity :many
SELECT
    pp.postcode::text AS postcode,
    c.slug AS category_slug,
    COALESCE((c.name->>'en')::text, c.slug) AS category_name,
    COUNT(DISTINCT pp.id)::int AS provider_count
FROM provider_profiles pp
JOIN provider_categories pc ON pc.provider_id = pp.id
JOIN categories c ON c.id = pc.category_id
WHERE pp.postcode IS NOT NULL
  AND pc.category_id IN (SELECT category_id FROM provider_categories WHERE provider_id = $1)
GROUP BY pp.postcode, c.slug, c.name
ORDER BY provider_count DESC
LIMIT 100
`

type GetCompetitorDensityRow struct {
	Postcode      string `json:"postcode"`
	CategorySlug  string `json:"category_slug"`
	CategoryName  string `json:"category_name"`
	ProviderCount int    `json:"provider_count"`
}

func (q *Queries) GetCompetitorDensity(ctx context.Context, providerID uuid.UUID) ([]GetCompetitorDensityRow, error) {
	rows, err := q.db.Query(ctx, getCompetitorDensity, providerID)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get competitor density")
		return nil, err
	}
	defer rows.Close()

	var items []GetCompetitorDensityRow
	for rows.Next() {
		var i GetCompetitorDensityRow
		if err := rows.Scan(&i.Postcode, &i.CategorySlug, &i.CategoryName, &i.ProviderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
