// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at FROM categories
WHERE is_active = true
ORDER BY sort_order, slug
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		log.Error().Err(err).Msg("failed to list categories")
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ParentID,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.RequiresLicense,
			&i.PricingModel,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan category row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating category rows")
		return nil, err
	}
	return items, nil
}

const listTopLevelCategories = `-- name: ListTopLevelCategories :many
SELECT id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at FROM categories
WHERE parent_id IS NULL AND is_active = true
ORDER BY sort_order, slug
`

func (q *Queries) ListTopLevelCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listTopLevelCategories)
	if err != nil {
		log.Error().Err(err).Msg("failed to list top level categories")
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ParentID,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.RequiresLicense,
			&i.PricingModel,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan top level category row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating top level category rows")
		return nil, err
	}
	return items, nil
}

const listSubcategories = `-- name: ListSubcategories :many
SELECT id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at FROM categories
WHERE parent_id = $1 AND is_active = true
ORDER BY sort_order, slug
`

func (q *Queries) ListSubcategories(ctx context.Context, parentID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubcategories, parentID)
	if err != nil {
		log.Error().Err(err).Str("parent_id", parentID.String()).Msg("failed to list subcategories")
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ParentID,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.RequiresLicense,
			&i.PricingModel,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan subcategory row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating subcategory rows")
		return nil, err
	}
	return items, nil
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.RequiresLicense,
		&i.PricingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("slug", slug).Msg("category not found by slug")
			return i, err
		}
		log.Error().Err(err).Str("slug", slug).Msg("failed to get category by slug")
		return i, err
	}
	return i, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.RequiresLicense,
		&i.PricingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("category_id", id.String()).Msg("category not found by id")
			return i, err
		}
		log.Error().Err(err).Str("category_id", id.String()).Msg("failed to get category by id")
		return i, err
	}
	return i, nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at
`

type CreateCategoryParams struct {
	Slug            string          `json:"slug"`
	Name            json.RawMessage `json:"name"`
	ParentID        *uuid.UUID      `json:"parent_id"`
	Icon            pgtype.Text     `json:"icon"`
	SortOrder       int32           `json:"sort_order"`
	IsActive        bool            `json:"is_active"`
	RequiresLicense bool            `json:"requires_license"`
	PricingModel    PricingModel    `json:"pricing_model"`
	Metadata        json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Slug,
		arg.Name,
		arg.ParentID,
		arg.Icon,
		arg.SortOrder,
		arg.IsActive,
		arg.RequiresLicense,
		arg.PricingModel,
		arg.Metadata,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.RequiresLicense,
		&i.PricingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("slug", arg.Slug).Msg("failed to create category")
		return i, err
	}
	return i, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = COALESCE($2, name),
    icon = COALESCE($3, icon),
    is_active = COALESCE($4, is_active),
    sort_order = COALESCE($5, sort_order),
    metadata = COALESCE($6, metadata)
WHERE id = $1
RETURNING id, slug, name, parent_id, icon, sort_order, is_active, requires_license, pricing_model, metadata, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      json.RawMessage `json:"name"`
	Icon      pgtype.Text     `json:"icon"`
	IsActive  pgtype.Bool     `json:"is_active"`
	SortOrder pgtype.Int4     `json:"sort_order"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.IsActive,
		arg.SortOrder,
		arg.Metadata,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.RequiresLicense,
		&i.PricingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("category_id", arg.ID.String()).Msg("failed to update category")
		return i, err
	}
	return i, nil
}

const countProvidersByCategory = `-- name: CountProvidersByCategory :many
SELECT c.id, c.slug, c.name, COUNT(pc.provider_id) as provider_count
FROM categories c
LEFT JOIN provider_categories pc ON pc.category_id = c.id
WHERE c.is_active = true
GROUP BY c.id, c.slug, c.name
ORDER BY provider_count DESC
`

type CountProvidersByCategoryRow struct {
	ID            uuid.UUID       `json:"id"`
	Slug          string          `json:"slug"`
	Name          json.RawMessage `json:"name"`
	ProviderCount int64           `json:"provider_count"`
}

func (q *Queries) CountProvidersByCategory(ctx context.Context) ([]CountProvidersByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countProvidersByCategory)
	if err != nil {
		log.Error().Err(err).Msg("failed to count providers by category")
		return nil, err
	}
	defer rows.Close()
	items := []CountProvidersByCategoryRow{}
	for rows.Next() {
		var i CountProvidersByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ProviderCount,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan providers by category row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating providers by category rows")
		return nil, err
	}
	return items, nil
}
