// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const getCropCatalogByJurisdiction = `-- name: GetCropCatalogByJurisdiction :many
SELECT id, jurisdiction_id, crop_slug, name, work_types, seasonal_calendar, metadata, is_active, created_at, updated_at FROM crop_catalog WHERE jurisdiction_id = $1 AND is_active = true ORDER BY crop_slug
`

func (q *Queries) GetCropCatalogByJurisdiction(ctx context.Context, jurisdictionID string) ([]CropCatalog, error) {
	rows, err := q.db.Query(ctx, getCropCatalogByJurisdiction, jurisdictionID)
	if err != nil {
		log.Error().Err(err).Str("jurisdiction_id", jurisdictionID).Msg("failed to get crop catalog by jurisdiction")
		return nil, err
	}
	defer rows.Close()

	items := []CropCatalog{}
	for rows.Next() {
		var i CropCatalog
		if err := rows.Scan(
			&i.ID,
			&i.JurisdictionID,
			&i.CropSlug,
			&i.Name,
			&i.WorkTypes,
			&i.SeasonalCalendar,
			&i.Metadata,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan crop catalog row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropBySlug = `-- name: GetCropBySlug :one
SELECT id, jurisdiction_id, crop_slug, name, work_types, seasonal_calendar, metadata, is_active, created_at, updated_at FROM crop_catalog WHERE jurisdiction_id = $1 AND crop_slug = $2
`

func (q *Queries) GetCropBySlug(ctx context.Context, jurisdictionID string, cropSlug string) (CropCatalog, error) {
	row := q.db.QueryRow(ctx, getCropBySlug, jurisdictionID, cropSlug)
	var i CropCatalog
	err := row.Scan(
		&i.ID,
		&i.JurisdictionID,
		&i.CropSlug,
		&i.Name,
		&i.WorkTypes,
		&i.SeasonalCalendar,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("jurisdiction_id", jurisdictionID).Str("crop_slug", cropSlug).Msg("crop not found")
			return i, err
		}
		log.Error().Err(err).Str("jurisdiction_id", jurisdictionID).Str("crop_slug", cropSlug).Msg("failed to get crop by slug")
		return i, err
	}
	return i, nil
}
