// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is the interface satisfied by both *pgx.Conn, pgx.Tx, and *pgxpool.Pool.
type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// Queries provides all the generated database query methods.
type Queries struct {
	db DBTX
}

// New creates a Queries instance backed by the given DBTX (pool, connection, or transaction).
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a new Queries instance that executes within the given transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
