// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

const registerDeviceToken = `-- name: RegisterDeviceToken :one
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET user_id = $1, platform = $3, is_active = true, updated_at = NOW()
RETURNING id, user_id, token, platform, is_active, created_at, updated_at
`

type RegisterDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) RegisterDeviceToken(ctx context.Context, arg RegisterDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, registerDeviceToken,
		arg.UserID,
		arg.Token,
		arg.Platform,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to register device token")
		return i, err
	}
	return i, nil
}

const getDeviceTokensForUser = `-- name: GetDeviceTokensForUser :many
SELECT id, user_id, token, platform, is_active, created_at, updated_at FROM device_tokens WHERE user_id = $1 AND is_active = true
`

func (q *Queries) GetDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensForUser, userID)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to get device tokens for user")
		return nil, err
	}
	defer rows.Close()

	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan device token row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

const deactivateDeviceToken = `-- name: DeactivateDeviceToken :exec
UPDATE device_tokens SET is_active = false WHERE token = $1
`

func (q *Queries) DeactivateDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deactivateDeviceToken, token)
	if err != nil {
		log.Error().Err(err).Msg("failed to deactivate device token")
	}
	return err
}
