// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (job_id, raised_by, against, type, severity, description, evidence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, raised_by, against, type, severity, status, description, evidence, resolution, resolved_by, resolution_amount, escalated_at, resolved_at, created_at, updated_at
`

type CreateDisputeParams struct {
	JobID       uuid.UUID       `json:"job_id"`
	RaisedBy    uuid.UUID       `json:"raised_by"`
	Against     uuid.UUID       `json:"against"`
	Type        DisputeType     `json:"type"`
	Severity    DisputeSeverity `json:"severity"`
	Description string          `json:"description"`
	Evidence    json.RawMessage `json:"evidence"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.JobID,
		arg.RaisedBy,
		arg.Against,
		arg.Type,
		arg.Severity,
		arg.Description,
		arg.Evidence,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RaisedBy,
		&i.Against,
		&i.Type,
		&i.Severity,
		&i.Status,
		&i.Description,
		&i.Evidence,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolutionAmount,
		&i.EscalatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to create dispute")
		return i, err
	}
	return i, nil
}

const getDisputeByID = `-- name: GetDisputeByID :one
SELECT d.id, d.job_id, d.raised_by, d.against, d.type, d.severity, d.status, d.description, d.evidence, d.resolution, d.resolved_by, d.resolution_amount, d.escalated_at, d.resolved_at, d.created_at, d.updated_at,
       rb.name as raised_by_name, ag.name as against_name,
       j.title as job_title
FROM disputes d
JOIN users rb ON rb.id = d.raised_by
JOIN users ag ON ag.id = d.against
JOIN jobs j ON j.id = d.job_id
WHERE d.id = $1
`

type GetDisputeByIDRow struct {
	Dispute
	RaisedByName pgtype.Text `json:"raised_by_name"`
	AgainstName  pgtype.Text `json:"against_name"`
	JobTitle     string      `json:"job_title"`
}

func (q *Queries) GetDisputeByID(ctx context.Context, id uuid.UUID) (GetDisputeByIDRow, error) {
	row := q.db.QueryRow(ctx, getDisputeByID, id)
	var i GetDisputeByIDRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RaisedBy,
		&i.Against,
		&i.Type,
		&i.Severity,
		&i.Status,
		&i.Description,
		&i.Evidence,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolutionAmount,
		&i.EscalatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RaisedByName,
		&i.AgainstName,
		&i.JobTitle,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("dispute_id", id.String()).Msg("dispute not found")
			return i, err
		}
		log.Error().Err(err).Str("dispute_id", id.String()).Msg("failed to get dispute by id")
		return i, err
	}
	return i, nil
}

const listDisputesByStatus = `-- name: ListDisputesByStatus :many
SELECT d.id, d.job_id, d.raised_by, d.against, d.type, d.severity, d.status, d.description, d.evidence, d.resolution, d.resolved_by, d.resolution_amount, d.escalated_at, d.resolved_at, d.created_at, d.updated_at,
       rb.name as raised_by_name, j.title as job_title
FROM disputes d
JOIN users rb ON rb.id = d.raised_by
JOIN jobs j ON j.id = d.job_id
WHERE d.status = $1
ORDER BY d.severity DESC, d.created_at ASC
LIMIT $2 OFFSET $3
`

type ListDisputesByStatusParams struct {
	Status DisputeStatus `json:"status"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListDisputesByStatusRow struct {
	Dispute
	RaisedByName pgtype.Text `json:"raised_by_name"`
	JobTitle     string      `json:"job_title"`
}

func (q *Queries) ListDisputesByStatus(ctx context.Context, arg ListDisputesByStatusParams) ([]ListDisputesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listDisputesByStatus,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("status", string(arg.Status)).Msg("failed to list disputes by status")
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesByStatusRow{}
	for rows.Next() {
		var i ListDisputesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RaisedBy,
			&i.Against,
			&i.Type,
			&i.Severity,
			&i.Status,
			&i.Description,
			&i.Evidence,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolutionAmount,
			&i.EscalatedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RaisedByName,
			&i.JobTitle,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan dispute row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating dispute rows")
		return nil, err
	}
	return items, nil
}

const updateDisputeStatus = `-- name: UpdateDisputeStatus :one
UPDATE disputes SET status = $2 WHERE id = $1
RETURNING id, job_id, raised_by, against, type, severity, status, description, evidence, resolution, resolved_by, resolution_amount, escalated_at, resolved_at, created_at, updated_at
`

type UpdateDisputeStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status DisputeStatus `json:"status"`
}

func (q *Queries) UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, updateDisputeStatus, arg.ID, arg.Status)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RaisedBy,
		&i.Against,
		&i.Type,
		&i.Severity,
		&i.Status,
		&i.Description,
		&i.Evidence,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolutionAmount,
		&i.EscalatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("dispute_id", arg.ID.String()).Msg("failed to update dispute status")
		return i, err
	}
	return i, nil
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE disputes
SET status = 'resolved',
    resolution = $2,
    resolved_by = $3,
    resolution_amount = $4,
    resolved_at = NOW()
WHERE id = $1
RETURNING id, job_id, raised_by, against, type, severity, status, description, evidence, resolution, resolved_by, resolution_amount, escalated_at, resolved_at, created_at, updated_at
`

type ResolveDisputeParams struct {
	ID               uuid.UUID      `json:"id"`
	Resolution       string         `json:"resolution"`
	ResolvedBy       uuid.UUID      `json:"resolved_by"`
	ResolutionAmount pgtype.Numeric `json:"resolution_amount"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.ID,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ResolutionAmount,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RaisedBy,
		&i.Against,
		&i.Type,
		&i.Severity,
		&i.Status,
		&i.Description,
		&i.Evidence,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolutionAmount,
		&i.EscalatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("dispute_id", arg.ID.String()).Msg("failed to resolve dispute")
		return i, err
	}
	return i, nil
}

const escalateDispute = `-- name: EscalateDispute :one
UPDATE disputes
SET status = 'escalated',
    severity = $2,
    escalated_at = NOW()
WHERE id = $1
RETURNING id, job_id, raised_by, against, type, severity, status, description, evidence, resolution, resolved_by, resolution_amount, escalated_at, resolved_at, created_at, updated_at
`

type EscalateDisputeParams struct {
	ID       uuid.UUID       `json:"id"`
	Severity DisputeSeverity `json:"severity"`
}

func (q *Queries) EscalateDispute(ctx context.Context, arg EscalateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, escalateDispute, arg.ID, arg.Severity)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RaisedBy,
		&i.Against,
		&i.Type,
		&i.Severity,
		&i.Status,
		&i.Description,
		&i.Evidence,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolutionAmount,
		&i.EscalatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("dispute_id", arg.ID.String()).Msg("failed to escalate dispute")
		return i, err
	}
	return i, nil
}
