// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

// EscrowTransaction represents a row in the escrow_transactions table.
type EscrowTransaction struct {
	ID               uuid.UUID          `json:"id"`
	JobID            uuid.UUID          `json:"job_id"`
	CustomerID       uuid.UUID          `json:"customer_id"`
	ProviderID       uuid.UUID          `json:"provider_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Status           EscrowStatus       `json:"status"`
	GatewayPaymentID pgtype.Text        `json:"gateway_payment_id"`
	HeldAt           time.Time          `json:"held_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	RefundedAt       pgtype.Timestamptz `json:"refunded_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

const createEscrowTransaction = `-- name: CreateEscrowTransaction :one
INSERT INTO escrow_transactions (job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id)
VALUES ($1, $2, $3, $4, $5, 'held', $6)
RETURNING id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at
`

type CreateEscrowTransactionParams struct {
	JobID            uuid.UUID      `json:"job_id"`
	CustomerID       uuid.UUID      `json:"customer_id"`
	ProviderID       uuid.UUID      `json:"provider_id"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	GatewayPaymentID pgtype.Text    `json:"gateway_payment_id"`
}

func (q *Queries) CreateEscrowTransaction(ctx context.Context, arg CreateEscrowTransactionParams) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, createEscrowTransaction,
		arg.JobID,
		arg.CustomerID,
		arg.ProviderID,
		arg.Amount,
		arg.Currency,
		arg.GatewayPaymentID,
	)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to create escrow transaction")
		return i, err
	}
	return i, nil
}

const getEscrowByID = `-- name: GetEscrowByID :one
SELECT id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at FROM escrow_transactions WHERE id = $1
`

func (q *Queries) GetEscrowByID(ctx context.Context, id uuid.UUID) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, getEscrowByID, id)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("escrow_id", id.String()).Msg("escrow transaction not found")
			return i, err
		}
		log.Error().Err(err).Str("escrow_id", id.String()).Msg("failed to get escrow by id")
		return i, err
	}
	return i, nil
}

const getEscrowByJobID = `-- name: GetEscrowByJobID :one
SELECT id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at FROM escrow_transactions WHERE job_id = $1
`

func (q *Queries) GetEscrowByJobID(ctx context.Context, jobID uuid.UUID) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, getEscrowByJobID, jobID)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("job_id", jobID.String()).Msg("escrow transaction not found for job")
			return i, err
		}
		log.Error().Err(err).Str("job_id", jobID.String()).Msg("failed to get escrow by job id")
		return i, err
	}
	return i, nil
}

const releaseEscrowTransaction = `-- name: ReleaseEscrowTransaction :one
UPDATE escrow_transactions
SET status = 'released', released_at = NOW()
WHERE id = $1 AND status = 'held'
RETURNING id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at
`

func (q *Queries) ReleaseEscrowTransaction(ctx context.Context, id uuid.UUID) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, releaseEscrowTransaction, id)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("escrow_id", id.String()).Msg("failed to release escrow transaction")
		return i, err
	}
	return i, nil
}

const refundEscrowTransaction = `-- name: RefundEscrowTransaction :one
UPDATE escrow_transactions
SET status = 'refunded', refunded_at = NOW()
WHERE id = $1 AND status IN ('held', 'disputed')
RETURNING id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at
`

func (q *Queries) RefundEscrowTransaction(ctx context.Context, id uuid.UUID) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, refundEscrowTransaction, id)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("escrow_id", id.String()).Msg("failed to refund escrow transaction")
		return i, err
	}
	return i, nil
}

const disputeEscrowTransaction = `-- name: DisputeEscrowTransaction :one
UPDATE escrow_transactions
SET status = 'disputed'
WHERE id = $1 AND status = 'held'
RETURNING id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at
`

func (q *Queries) DisputeEscrowTransaction(ctx context.Context, id uuid.UUID) (EscrowTransaction, error) {
	row := q.db.QueryRow(ctx, disputeEscrowTransaction, id)
	var i EscrowTransaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CustomerID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.GatewayPaymentID,
		&i.HeldAt,
		&i.ReleasedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("escrow_id", id.String()).Msg("failed to dispute escrow transaction")
		return i, err
	}
	return i, nil
}

const listEscrowByUser = `-- name: ListEscrowByUser :many
SELECT id, job_id, customer_id, provider_id, amount, currency, status, gateway_payment_id, held_at, released_at, refunded_at, created_at, updated_at FROM escrow_transactions
WHERE customer_id = $1 OR provider_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListEscrowByUser(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]EscrowTransaction, error) {
	rows, err := q.db.Query(ctx, listEscrowByUser, userID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to list escrow transactions for user")
		return nil, err
	}
	defer rows.Close()

	items := []EscrowTransaction{}
	for rows.Next() {
		var i EscrowTransaction
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CustomerID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.GatewayPaymentID,
			&i.HeldAt,
			&i.ReleasedAt,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan escrow transaction row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}
