// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createJobQuote = `-- name: CreateJobQuote :one
INSERT INTO job_quotes (job_id, provider_id, amount, currency, message, estimated_duration_hours, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, provider_id, amount, currency, message, estimated_duration_hours, is_accepted, expires_at, created_at
`

type CreateJobQuoteParams struct {
	JobID                  uuid.UUID          `json:"job_id"`
	ProviderID             uuid.UUID          `json:"provider_id"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               string             `json:"currency"`
	Message                pgtype.Text        `json:"message"`
	EstimatedDurationHours pgtype.Numeric     `json:"estimated_duration_hours"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateJobQuote(ctx context.Context, arg CreateJobQuoteParams) (JobQuote, error) {
	row := q.db.QueryRow(ctx, createJobQuote,
		arg.JobID,
		arg.ProviderID,
		arg.Amount,
		arg.Currency,
		arg.Message,
		arg.EstimatedDurationHours,
		arg.ExpiresAt,
	)
	var i JobQuote
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Message,
		&i.EstimatedDurationHours,
		&i.IsAccepted,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to create job quote")
		return i, err
	}
	return i, nil
}

const getJobQuoteByID = `-- name: GetJobQuoteByID :one
SELECT id, job_id, provider_id, amount, currency, message, estimated_duration_hours, is_accepted, expires_at, created_at FROM job_quotes WHERE id = $1
`

func (q *Queries) GetJobQuoteByID(ctx context.Context, id uuid.UUID) (JobQuote, error) {
	row := q.db.QueryRow(ctx, getJobQuoteByID, id)
	var i JobQuote
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Message,
		&i.EstimatedDurationHours,
		&i.IsAccepted,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("quote_id", id.String()).Msg("job quote not found")
			return i, err
		}
		log.Error().Err(err).Str("quote_id", id.String()).Msg("failed to get job quote by id")
		return i, err
	}
	return i, nil
}

const listQuotesByJob = `-- name: ListQuotesByJob :many
SELECT id, job_id, provider_id, amount, currency, message, estimated_duration_hours, is_accepted, expires_at, created_at FROM job_quotes WHERE job_id = $1 ORDER BY created_at
`

func (q *Queries) ListQuotesByJob(ctx context.Context, jobID uuid.UUID) ([]JobQuote, error) {
	rows, err := q.db.Query(ctx, listQuotesByJob, jobID)
	if err != nil {
		log.Error().Err(err).Str("job_id", jobID.String()).Msg("failed to list quotes by job")
		return nil, err
	}
	defer rows.Close()

	items := []JobQuote{}
	for rows.Next() {
		var i JobQuote
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.Message,
			&i.EstimatedDurationHours,
			&i.IsAccepted,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job quote row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotesByProvider = `-- name: ListQuotesByProvider :many
SELECT id, job_id, provider_id, amount, currency, message, estimated_duration_hours, is_accepted, expires_at, created_at FROM job_quotes WHERE provider_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

func (q *Queries) ListQuotesByProvider(ctx context.Context, providerID uuid.UUID, limit int32, offset int32) ([]JobQuote, error) {
	rows, err := q.db.Query(ctx, listQuotesByProvider, providerID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to list quotes by provider")
		return nil, err
	}
	defer rows.Close()

	items := []JobQuote{}
	for rows.Next() {
		var i JobQuote
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ProviderID,
			&i.Amount,
			&i.Currency,
			&i.Message,
			&i.EstimatedDurationHours,
			&i.IsAccepted,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job quote row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const acceptJobQuote = `-- name: AcceptJobQuote :one
UPDATE job_quotes SET is_accepted = true WHERE id = $1
RETURNING id, job_id, provider_id, amount, currency, message, estimated_duration_hours, is_accepted, expires_at, created_at
`

func (q *Queries) AcceptJobQuote(ctx context.Context, id uuid.UUID) (JobQuote, error) {
	row := q.db.QueryRow(ctx, acceptJobQuote, id)
	var i JobQuote
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ProviderID,
		&i.Amount,
		&i.Currency,
		&i.Message,
		&i.EstimatedDurationHours,
		&i.IsAccepted,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("quote_id", id.String()).Msg("failed to accept job quote")
		return i, err
	}
	return i, nil
}
