// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (customer_id, category_id, title, description, postcode, location, address, urgency, scheduled_at, currency, payment_method, is_recurring, recurrence_rule, jurisdiction_id, photos)
VALUES ($1, $2, $3, $4, $5, ST_MakePoint($6, $7)::geography, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, customer_id, provider_id, category_id, title, description, postcode, location, address, status, urgency, scheduled_at, started_at, completed_at, quoted_price, final_price, currency, payment_method, is_recurring, recurrence_rule, photos, completion_photos, jurisdiction_id, metadata, created_at, updated_at
`

type CreateJobParams struct {
	CustomerID     uuid.UUID          `json:"customer_id"`
	CategoryID     uuid.UUID          `json:"category_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Postcode       pgtype.Text        `json:"postcode"`
	Longitude      float64            `json:"longitude"`
	Latitude       float64            `json:"latitude"`
	Address        pgtype.Text        `json:"address"`
	Urgency        pgtype.Text        `json:"urgency"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	Currency       string             `json:"currency"`
	PaymentMethod  PaymentMethod      `json:"payment_method"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurrenceRule json.RawMessage    `json:"recurrence_rule"`
	JurisdictionID string             `json:"jurisdiction_id"`
	Photos         []string           `json:"photos"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CustomerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Postcode,
		arg.Longitude,
		arg.Latitude,
		arg.Address,
		arg.Urgency,
		arg.ScheduledAt,
		arg.Currency,
		arg.PaymentMethod,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.JurisdictionID,
		arg.Photos,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Postcode,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Urgency,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QuotedPrice,
		&i.FinalPrice,
		&i.Currency,
		&i.PaymentMethod,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Photos,
		&i.CompletionPhotos,
		&i.JurisdictionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("customer_id", arg.CustomerID.String()).Msg("failed to create job")
		return i, err
	}
	return i, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT j.id, j.customer_id, j.provider_id, j.category_id, j.title, j.description, j.postcode, j.location, j.address, j.status, j.urgency, j.scheduled_at, j.started_at, j.completed_at, j.quoted_price, j.final_price, j.currency, j.payment_method, j.is_recurring, j.recurrence_rule, j.photos, j.completion_photos, j.jurisdiction_id, j.metadata, j.created_at, j.updated_at,
       cu.name as customer_name, cu.phone as customer_phone,
       pu.name as provider_name, pu.phone as provider_phone,
       c.slug as category_slug, c.name as category_name
FROM jobs j
JOIN users cu ON cu.id = j.customer_id
LEFT JOIN users pu ON pu.id = j.provider_id
JOIN categories c ON c.id = j.category_id
WHERE j.id = $1
`

type GetJobByIDRow struct {
	Job
	CustomerName pgtype.Text     `json:"customer_name"`
	CustomerPhone string         `json:"customer_phone"`
	ProviderName pgtype.Text     `json:"provider_name"`
	ProviderPhone pgtype.Text    `json:"provider_phone"`
	CategorySlug string          `json:"category_slug"`
	CategoryName json.RawMessage `json:"category_name"`
}

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Postcode,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Urgency,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QuotedPrice,
		&i.FinalPrice,
		&i.Currency,
		&i.PaymentMethod,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Photos,
		&i.CompletionPhotos,
		&i.JurisdictionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ProviderName,
		&i.ProviderPhone,
		&i.CategorySlug,
		&i.CategoryName,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("job_id", id.String()).Msg("job not found")
			return i, err
		}
		log.Error().Err(err).Str("job_id", id.String()).Msg("failed to get job by id")
		return i, err
	}
	return i, nil
}

const listJobsByCustomer = `-- name: ListJobsByCustomer :many
SELECT j.id, j.customer_id, j.provider_id, j.category_id, j.title, j.description, j.postcode, j.location, j.address, j.status, j.urgency, j.scheduled_at, j.started_at, j.completed_at, j.quoted_price, j.final_price, j.currency, j.payment_method, j.is_recurring, j.recurrence_rule, j.photos, j.completion_photos, j.jurisdiction_id, j.metadata, j.created_at, j.updated_at,
       c.slug as category_slug, c.name as category_name
FROM jobs j
JOIN categories c ON c.id = j.category_id
WHERE j.customer_id = $1
ORDER BY j.created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByCustomerParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListJobsByCustomerRow struct {
	Job
	CategorySlug string          `json:"category_slug"`
	CategoryName json.RawMessage `json:"category_name"`
}

func (q *Queries) ListJobsByCustomer(ctx context.Context, arg ListJobsByCustomerParams) ([]ListJobsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listJobsByCustomer,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("customer_id", arg.CustomerID.String()).Msg("failed to list jobs by customer")
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByCustomerRow{}
	for rows.Next() {
		var i ListJobsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Postcode,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Urgency,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QuotedPrice,
			&i.FinalPrice,
			&i.Currency,
			&i.PaymentMethod,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Photos,
			&i.CompletionPhotos,
			&i.JurisdictionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job customer row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating job customer rows")
		return nil, err
	}
	return items, nil
}

const listJobsByProvider = `-- name: ListJobsByProvider :many
SELECT j.id, j.customer_id, j.provider_id, j.category_id, j.title, j.description, j.postcode, j.location, j.address, j.status, j.urgency, j.scheduled_at, j.started_at, j.completed_at, j.quoted_price, j.final_price, j.currency, j.payment_method, j.is_recurring, j.recurrence_rule, j.photos, j.completion_photos, j.jurisdiction_id, j.metadata, j.created_at, j.updated_at,
       c.slug as category_slug, c.name as category_name,
       cu.name as customer_name
FROM jobs j
JOIN categories c ON c.id = j.category_id
JOIN users cu ON cu.id = j.customer_id
WHERE j.provider_id = $1
ORDER BY j.created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListJobsByProviderRow struct {
	Job
	CategorySlug string          `json:"category_slug"`
	CategoryName json.RawMessage `json:"category_name"`
	CustomerName pgtype.Text     `json:"customer_name"`
}

func (q *Queries) ListJobsByProvider(ctx context.Context, arg ListJobsByProviderParams) ([]ListJobsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listJobsByProvider,
		arg.ProviderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("provider_id", arg.ProviderID.String()).Msg("failed to list jobs by provider")
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByProviderRow{}
	for rows.Next() {
		var i ListJobsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Postcode,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Urgency,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QuotedPrice,
			&i.FinalPrice,
			&i.Currency,
			&i.PaymentMethod,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Photos,
			&i.CompletionPhotos,
			&i.JurisdictionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CustomerName,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job provider row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating job provider rows")
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT j.id, j.customer_id, j.provider_id, j.category_id, j.title, j.description, j.postcode, j.location, j.address, j.status, j.urgency, j.scheduled_at, j.started_at, j.completed_at, j.quoted_price, j.final_price, j.currency, j.payment_method, j.is_recurring, j.recurrence_rule, j.photos, j.completion_photos, j.jurisdiction_id, j.metadata, j.created_at, j.updated_at,
       c.slug as category_slug, c.name as category_name
FROM jobs j
JOIN categories c ON c.id = j.category_id
WHERE j.status = $1
  AND j.jurisdiction_id = $2
ORDER BY j.created_at DESC
LIMIT $3 OFFSET $4
`

type ListJobsByStatusParams struct {
	Status         JobStatus `json:"status"`
	JurisdictionID string    `json:"jurisdiction_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListJobsByStatusRow struct {
	Job
	CategorySlug string          `json:"category_slug"`
	CategoryName json.RawMessage `json:"category_name"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]ListJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus,
		arg.Status,
		arg.JurisdictionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("status", string(arg.Status)).Msg("failed to list jobs by status")
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByStatusRow{}
	for rows.Next() {
		var i ListJobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Postcode,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Urgency,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QuotedPrice,
			&i.FinalPrice,
			&i.Currency,
			&i.PaymentMethod,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Photos,
			&i.CompletionPhotos,
			&i.JurisdictionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job status row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating job status rows")
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = $2 WHERE id = $1
RETURNING id, customer_id, provider_id, category_id, title, description, postcode, location, address, status, urgency, scheduled_at, started_at, completed_at, quoted_price, final_price, currency, payment_method, is_recurring, recurrence_rule, photos, completion_photos, jurisdiction_id, metadata, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status JobStatus `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Postcode,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Urgency,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QuotedPrice,
		&i.FinalPrice,
		&i.Currency,
		&i.PaymentMethod,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Photos,
		&i.CompletionPhotos,
		&i.JurisdictionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.ID.String()).Msg("failed to update job status")
		return i, err
	}
	return i, nil
}

const assignProvider = `-- name: AssignProvider :one
UPDATE jobs SET provider_id = $2, status = 'accepted' WHERE id = $1
RETURNING id, customer_id, provider_id, category_id, title, description, postcode, location, address, status, urgency, scheduled_at, started_at, completed_at, quoted_price, final_price, currency, payment_method, is_recurring, recurrence_rule, photos, completion_photos, jurisdiction_id, metadata, created_at, updated_at
`

type AssignProviderParams struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
}

func (q *Queries) AssignProvider(ctx context.Context, arg AssignProviderParams) (Job, error) {
	row := q.db.QueryRow(ctx, assignProvider, arg.ID, arg.ProviderID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Postcode,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Urgency,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QuotedPrice,
		&i.FinalPrice,
		&i.Currency,
		&i.PaymentMethod,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Photos,
		&i.CompletionPhotos,
		&i.JurisdictionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.ID.String()).Msg("failed to assign provider")
		return i, err
	}
	return i, nil
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs
SET status = 'completed',
    completed_at = NOW(),
    final_price = $2,
    completion_photos = $3
WHERE id = $1
RETURNING id, customer_id, provider_id, category_id, title, description, postcode, location, address, status, urgency, scheduled_at, started_at, completed_at, quoted_price, final_price, currency, payment_method, is_recurring, recurrence_rule, photos, completion_photos, jurisdiction_id, metadata, created_at, updated_at
`

type CompleteJobParams struct {
	ID               uuid.UUID      `json:"id"`
	FinalPrice       pgtype.Numeric `json:"final_price"`
	CompletionPhotos []string       `json:"completion_photos"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.FinalPrice, arg.CompletionPhotos)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Postcode,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Urgency,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QuotedPrice,
		&i.FinalPrice,
		&i.Currency,
		&i.PaymentMethod,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Photos,
		&i.CompletionPhotos,
		&i.JurisdictionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.ID.String()).Msg("failed to complete job")
		return i, err
	}
	return i, nil
}

const searchJobsByLocation = `-- name: SearchJobsByLocation :many
SELECT j.id, j.customer_id, j.provider_id, j.category_id, j.title, j.description, j.postcode, j.location, j.address, j.status, j.urgency, j.scheduled_at, j.started_at, j.completed_at, j.quoted_price, j.final_price, j.currency, j.payment_method, j.is_recurring, j.recurrence_rule, j.photos, j.completion_photos, j.jurisdiction_id, j.metadata, j.created_at, j.updated_at,
       c.slug as category_slug, c.name as category_name,
       ST_Distance(j.location, ST_MakePoint($1, $2)::geography) as distance_meters
FROM jobs j
JOIN categories c ON c.id = j.category_id
WHERE ST_DWithin(j.location, ST_MakePoint($1, $2)::geography, $3)
  AND j.status = 'posted'
ORDER BY j.created_at DESC
LIMIT $4 OFFSET $5
`

type SearchJobsByLocationParams struct {
	Longitude    float64 `json:"longitude"`
	Latitude     float64 `json:"latitude"`
	RadiusMeters float64 `json:"radius_meters"`
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
}

type SearchJobsByLocationRow struct {
	Job
	CategorySlug   string          `json:"category_slug"`
	CategoryName   json.RawMessage `json:"category_name"`
	DistanceMeters float64         `json:"distance_meters"`
}

func (q *Queries) SearchJobsByLocation(ctx context.Context, arg SearchJobsByLocationParams) ([]SearchJobsByLocationRow, error) {
	rows, err := q.db.Query(ctx, searchJobsByLocation,
		arg.Longitude,
		arg.Latitude,
		arg.RadiusMeters,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to search jobs by location")
		return nil, err
	}
	defer rows.Close()
	items := []SearchJobsByLocationRow{}
	for rows.Next() {
		var i SearchJobsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Postcode,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Urgency,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QuotedPrice,
			&i.FinalPrice,
			&i.Currency,
			&i.PaymentMethod,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Photos,
			&i.CompletionPhotos,
			&i.JurisdictionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.DistanceMeters,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan job location row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating job location rows")
		return nil, err
	}
	return items, nil
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs WHERE status = $1 AND jurisdiction_id = $2
`

type CountJobsByStatusParams struct {
	Status         JobStatus `json:"status"`
	JurisdictionID string    `json:"jurisdiction_id"`
}

func (q *Queries) CountJobsByStatus(ctx context.Context, arg CountJobsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByStatus, arg.Status, arg.JurisdictionID)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("status", string(arg.Status)).Msg("failed to count jobs by status")
		return 0, err
	}
	return count, nil
}
