// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const getJurisdiction = `-- name: GetJurisdiction :one
SELECT id, name, default_language, currency, currency_symbol, phone_prefix, timezone, is_active, config, created_at, updated_at FROM jurisdictions WHERE id = $1
`

func (q *Queries) GetJurisdiction(ctx context.Context, id string) (Jurisdiction, error) {
	row := q.db.QueryRow(ctx, getJurisdiction, id)
	var i Jurisdiction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultLanguage,
		&i.Currency,
		&i.CurrencySymbol,
		&i.PhonePrefix,
		&i.Timezone,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return i, err
		}
		log.Error().Err(err).Str("id", id).Msg("failed to get jurisdiction")
		return i, err
	}
	return i, nil
}

const listActiveJurisdictions = `-- name: ListActiveJurisdictions :many
SELECT id, name, default_language, currency, currency_symbol, phone_prefix, timezone, is_active, config, created_at, updated_at FROM jurisdictions WHERE is_active = true ORDER BY name
`

func (q *Queries) ListActiveJurisdictions(ctx context.Context) ([]Jurisdiction, error) {
	rows, err := q.db.Query(ctx, listActiveJurisdictions)
	if err != nil {
		log.Error().Err(err).Msg("failed to list active jurisdictions")
		return nil, err
	}
	defer rows.Close()

	items := []Jurisdiction{}
	for rows.Next() {
		var i Jurisdiction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultLanguage,
			&i.Currency,
			&i.CurrencySymbol,
			&i.PhonePrefix,
			&i.Timezone,
			&i.IsActive,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan jurisdiction row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

const updateJurisdictionConfig = `-- name: UpdateJurisdictionConfig :exec
UPDATE jurisdictions SET config = $2 WHERE id = $1
`

func (q *Queries) UpdateJurisdictionConfig(ctx context.Context, id string, config json.RawMessage) error {
	_, err := q.db.Exec(ctx, updateJurisdictionConfig, id, config)
	if err != nil {
		log.Error().Err(err).Str("id", id).Msg("failed to update jurisdiction config")
	}
	return err
}
