// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// --- Enum types matching the database enums ---

type UserType string

const (
	UserTypeCustomer UserType = "customer"
	UserTypeProvider UserType = "provider"
	UserTypeCompany  UserType = "company"
)

type DeviceType string

const (
	DeviceTypeSmartphone DeviceType = "smartphone"
	DeviceTypeBasicPhone DeviceType = "basic_phone"
	DeviceTypeWeb        DeviceType = "web"
)

type VerificationStatus string

const (
	VerificationStatusUnverified VerificationStatus = "unverified"
	VerificationStatusPending    VerificationStatus = "pending"
	VerificationStatusVerified   VerificationStatus = "verified"
	VerificationStatusRejected   VerificationStatus = "rejected"
)

type ProviderLevel string

const (
	ProviderLevelNew            ProviderLevel = "new"
	ProviderLevelActive         ProviderLevel = "active"
	ProviderLevelTrusted        ProviderLevel = "trusted"
	ProviderLevelExpert         ProviderLevel = "expert"
	ProviderLevelLocalChampion  ProviderLevel = "local_champion"
)

type SubscriptionTier string

const (
	SubscriptionTierFree         SubscriptionTier = "free"
	SubscriptionTierBasic        SubscriptionTier = "basic"
	SubscriptionTierProfessional SubscriptionTier = "professional"
	SubscriptionTierEnterprise   SubscriptionTier = "enterprise"
)

type JobStatus string

const (
	JobStatusDraft      JobStatus = "draft"
	JobStatusPosted     JobStatus = "posted"
	JobStatusMatched    JobStatus = "matched"
	JobStatusQuoted     JobStatus = "quoted"
	JobStatusAccepted   JobStatus = "accepted"
	JobStatusInProgress JobStatus = "in_progress"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusCancelled  JobStatus = "cancelled"
	JobStatusDisputed   JobStatus = "disputed"
)

type PaymentMethod string

const (
	PaymentMethodOnline PaymentMethod = "online"
	PaymentMethodCash   PaymentMethod = "cash"
	PaymentMethodWallet PaymentMethod = "wallet"
)

type PaymentStatus string

const (
	PaymentStatusPending            PaymentStatus = "pending"
	PaymentStatusAuthorized         PaymentStatus = "authorized"
	PaymentStatusCaptured           PaymentStatus = "captured"
	PaymentStatusFailed             PaymentStatus = "failed"
	PaymentStatusRefunded           PaymentStatus = "refunded"
	PaymentStatusPartiallyRefunded  PaymentStatus = "partially_refunded"
)

type EscrowStatus string

const (
	EscrowStatusHeld     EscrowStatus = "held"
	EscrowStatusReleased EscrowStatus = "released"
	EscrowStatusRefunded EscrowStatus = "refunded"
	EscrowStatusDisputed EscrowStatus = "disputed"
)

type DisputeType string

const (
	DisputeTypeQuality    DisputeType = "quality"
	DisputeTypeNoShow     DisputeType = "no_show"
	DisputeTypeLateArrival DisputeType = "late_arrival"
	DisputeTypeOvercharge DisputeType = "overcharge"
	DisputeTypeNonPayment DisputeType = "non_payment"
	DisputeTypeDamage     DisputeType = "damage"
	DisputeTypeHarassment DisputeType = "harassment"
	DisputeTypeOther      DisputeType = "other"
)

type DisputeSeverity string

const (
	DisputeSeverityLow      DisputeSeverity = "low"
	DisputeSeverityMedium   DisputeSeverity = "medium"
	DisputeSeverityHigh     DisputeSeverity = "high"
	DisputeSeverityCritical DisputeSeverity = "critical"
)

type DisputeStatus string

const (
	DisputeStatusOpen        DisputeStatus = "open"
	DisputeStatusUnderReview DisputeStatus = "under_review"
	DisputeStatusMediation   DisputeStatus = "mediation"
	DisputeStatusEscalated   DisputeStatus = "escalated"
	DisputeStatusResolved    DisputeStatus = "resolved"
	DisputeStatusClosed      DisputeStatus = "closed"
)

type ModerationStatus string

const (
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusRejected ModerationStatus = "rejected"
	ModerationStatusFlagged  ModerationStatus = "flagged"
)

type PricingModel string

const (
	PricingModelHourly     PricingModel = "hourly"
	PricingModelFixed      PricingModel = "fixed"
	PricingModelPerSqft    PricingModel = "per_sqft"
	PricingModelPerUnit    PricingModel = "per_unit"
	PricingModelPerTree    PricingModel = "per_tree"
	PricingModelPerDay     PricingModel = "per_day"
	PricingModelNegotiable PricingModel = "negotiable"
)

// --- Table models ---

type Jurisdiction struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	DefaultLanguage string          `json:"default_language"`
	Currency        string          `json:"currency"`
	CurrencySymbol  string          `json:"currency_symbol"`
	PhonePrefix     string          `json:"phone_prefix"`
	Timezone        string          `json:"timezone"`
	IsActive        bool            `json:"is_active"`
	Config          json.RawMessage `json:"config"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Type              UserType           `json:"type"`
	Phone             string             `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	Name              pgtype.Text        `json:"name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	JurisdictionID    string             `json:"jurisdiction_id"`
	PreferredLanguage string             `json:"preferred_language"`
	DeviceType        DeviceType         `json:"device_type"`
	IsActive          bool               `json:"is_active"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type ProviderProfile struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	BusinessName           pgtype.Text        `json:"business_name"`
	Description            pgtype.Text        `json:"description"`
	Skills                 []string           `json:"skills"`
	ServiceRadiusKM        pgtype.Numeric     `json:"service_radius_km"`
	Postcode               pgtype.Text        `json:"postcode"`
	Location               pgtype.Text        `json:"location"`
	TrustScore             pgtype.Numeric     `json:"trust_score"`
	Level                  ProviderLevel      `json:"level"`
	VerificationStatus     VerificationStatus `json:"verification_status"`
	SubscriptionTier       SubscriptionTier   `json:"subscription_tier"`
	TotalJobsCompleted     int32              `json:"total_jobs_completed"`
	TotalReviews           int32              `json:"total_reviews"`
	AvgResponseTimeMinutes pgtype.Int4        `json:"avg_response_time_minutes"`
	AvailabilitySchedule   json.RawMessage    `json:"availability_schedule"`
	Documents              json.RawMessage    `json:"documents"`
	BankAccountID          pgtype.Text        `json:"bank_account_id"`
	WalletBalance          pgtype.Numeric     `json:"wallet_balance"`
	IsAvailable            bool               `json:"is_available"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type Category struct {
	ID              uuid.UUID       `json:"id"`
	Slug            string          `json:"slug"`
	Name            json.RawMessage `json:"name"`
	ParentID        *uuid.UUID      `json:"parent_id"`
	Icon            pgtype.Text     `json:"icon"`
	SortOrder       int32           `json:"sort_order"`
	IsActive        bool            `json:"is_active"`
	RequiresLicense bool            `json:"requires_license"`
	PricingModel    PricingModel    `json:"pricing_model"`
	Metadata        json.RawMessage `json:"metadata"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ProviderCategory struct {
	ProviderID      uuid.UUID `json:"provider_id"`
	CategoryID      uuid.UUID `json:"category_id"`
	YearsExperience pgtype.Int4 `json:"years_experience"`
	IsPrimary       bool      `json:"is_primary"`
	CreatedAt       time.Time `json:"created_at"`
}

type Job struct {
	ID               uuid.UUID          `json:"id"`
	CustomerID       uuid.UUID          `json:"customer_id"`
	ProviderID       *uuid.UUID         `json:"provider_id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Postcode         pgtype.Text        `json:"postcode"`
	Location         pgtype.Text        `json:"location"`
	Address          pgtype.Text        `json:"address"`
	Status           JobStatus          `json:"status"`
	Urgency          pgtype.Text        `json:"urgency"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	QuotedPrice      pgtype.Numeric     `json:"quoted_price"`
	FinalPrice       pgtype.Numeric     `json:"final_price"`
	Currency         string             `json:"currency"`
	PaymentMethod    PaymentMethod      `json:"payment_method"`
	IsRecurring      bool               `json:"is_recurring"`
	RecurrenceRule   json.RawMessage    `json:"recurrence_rule"`
	Photos           []string           `json:"photos"`
	CompletionPhotos []string           `json:"completion_photos"`
	JurisdictionID   string             `json:"jurisdiction_id"`
	Metadata         json.RawMessage    `json:"metadata"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type JobQuote struct {
	ID                     uuid.UUID          `json:"id"`
	JobID                  uuid.UUID          `json:"job_id"`
	ProviderID             uuid.UUID          `json:"provider_id"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               string             `json:"currency"`
	Message                pgtype.Text        `json:"message"`
	EstimatedDurationHours pgtype.Numeric     `json:"estimated_duration_hours"`
	IsAccepted             bool               `json:"is_accepted"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedAt              time.Time          `json:"created_at"`
}

type Transaction struct {
	ID                   uuid.UUID          `json:"id"`
	JobID                uuid.UUID          `json:"job_id"`
	Amount               pgtype.Numeric     `json:"amount"`
	Currency             string             `json:"currency"`
	CommissionRate       pgtype.Numeric     `json:"commission_rate"`
	CommissionAmount     pgtype.Numeric     `json:"commission_amount"`
	TaxAmount            pgtype.Numeric     `json:"tax_amount"`
	ProviderPayoutAmount pgtype.Numeric     `json:"provider_payout_amount"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	EscrowStatus         *EscrowStatus      `json:"escrow_status"`
	PaymentGateway       pgtype.Text        `json:"payment_gateway"`
	GatewayOrderID       pgtype.Text        `json:"gateway_order_id"`
	GatewayPaymentID     pgtype.Text        `json:"gateway_payment_id"`
	GatewaySignature     pgtype.Text        `json:"gateway_signature"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	SettledAt            pgtype.Timestamptz `json:"settled_at"`
	RefundAmount         pgtype.Numeric     `json:"refund_amount"`
	RefundedAt           pgtype.Timestamptz `json:"refunded_at"`
	Metadata             json.RawMessage    `json:"metadata"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type Review struct {
	ID               uuid.UUID          `json:"id"`
	JobID            uuid.UUID          `json:"job_id"`
	ReviewerID       uuid.UUID          `json:"reviewer_id"`
	RevieweeID       uuid.UUID          `json:"reviewee_id"`
	Rating           int16              `json:"rating"`
	Comment          pgtype.Text        `json:"comment"`
	Language         pgtype.Text        `json:"language"`
	Photos           []string           `json:"photos"`
	ModerationStatus ModerationStatus   `json:"moderation_status"`
	IsPublic         bool               `json:"is_public"`
	Response         pgtype.Text        `json:"response"`
	RespondedAt      pgtype.Timestamptz `json:"responded_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type Dispute struct {
	ID               uuid.UUID          `json:"id"`
	JobID            uuid.UUID          `json:"job_id"`
	RaisedBy         uuid.UUID          `json:"raised_by"`
	Against          uuid.UUID          `json:"against"`
	Type             DisputeType        `json:"type"`
	Severity         DisputeSeverity    `json:"severity"`
	Status           DisputeStatus      `json:"status"`
	Description      string             `json:"description"`
	Evidence         json.RawMessage    `json:"evidence"`
	Resolution       pgtype.Text        `json:"resolution"`
	ResolvedBy       *uuid.UUID         `json:"resolved_by"`
	ResolutionAmount pgtype.Numeric     `json:"resolution_amount"`
	EscalatedAt      pgtype.Timestamptz `json:"escalated_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type PointsLedger struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Points        int32       `json:"points"`
	Reason        string      `json:"reason"`
	ReferenceID   *uuid.UUID  `json:"reference_id"`
	ReferenceType pgtype.Text `json:"reference_type"`
	BalanceAfter  int32       `json:"balance_after"`
	CreatedAt     time.Time   `json:"created_at"`
}

type OtpCode struct {
	ID          uuid.UUID          `json:"id"`
	Phone       string             `json:"phone"`
	Code        string             `json:"code"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   time.Time          `json:"expires_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      pgtype.Text        `json:"body"`
	Data      json.RawMessage    `json:"data"`
	Channel   string             `json:"channel"`
	IsRead    bool               `json:"is_read"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type ProviderAvailability struct {
	ID          uuid.UUID `json:"id"`
	ProviderID  uuid.UUID `json:"provider_id"`
	DayOfWeek   int16     `json:"day_of_week"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	IsAvailable bool      `json:"is_available"`
	CreatedAt   time.Time `json:"created_at"`
}

type CropCatalog struct {
	ID               uuid.UUID       `json:"id"`
	JurisdictionID   string          `json:"jurisdiction_id"`
	CropSlug         string          `json:"crop_slug"`
	Name             json.RawMessage `json:"name"`
	WorkTypes        json.RawMessage `json:"work_types"`
	SeasonalCalendar json.RawMessage `json:"seasonal_calendar"`
	Metadata         json.RawMessage `json:"metadata"`
	IsActive         bool            `json:"is_active"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Route struct {
	ID           uuid.UUID      `json:"id"`
	ProviderID   uuid.UUID      `json:"provider_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	Postcodes    []string       `json:"postcodes"`
	Frequency    string         `json:"frequency"`
	DayOfWeek    pgtype.Int2    `json:"day_of_week"`
	MaxStops     int32          `json:"max_stops"`
	CurrentStops int32          `json:"current_stops"`
	PricePerStop pgtype.Numeric `json:"price_per_stop"`
	Currency     string         `json:"currency"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type RouteStop struct {
	ID         uuid.UUID   `json:"id"`
	RouteID    uuid.UUID   `json:"route_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	Address    string      `json:"address"`
	Location   pgtype.Text `json:"location"`
	StopOrder  int32       `json:"stop_order"`
	Notes      pgtype.Text `json:"notes"`
	IsActive   bool        `json:"is_active"`
	CreatedAt  time.Time   `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	UserID     *uuid.UUID      `json:"user_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   *uuid.UUID      `json:"entity_id"`
	OldValues  json.RawMessage `json:"old_values"`
	NewValues  json.RawMessage `json:"new_values"`
	IpAddress  pgtype.Text     `json:"ip_address"`
	UserAgent  pgtype.Text     `json:"user_agent"`
	CreatedAt  time.Time       `json:"created_at"`
}

type DeviceToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	Platform  string    `json:"platform"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
