// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, data, channel)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, title, body, data, channel, is_read, sent_at, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  uuid.UUID       `json:"user_id"`
	Type    string          `json:"type"`
	Title   string          `json:"title"`
	Body    pgtype.Text     `json:"body"`
	Data    json.RawMessage `json:"data"`
	Channel string          `json:"channel"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.Channel,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Channel,
		&i.IsRead,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to create notification")
		return i, err
	}
	return i, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, type, title, body, data, channel, is_read, sent_at, read_at, created_at FROM notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to list unread notifications")
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Channel,
			&i.IsRead,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan notification row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating notification rows")
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = true, read_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		log.Error().Err(err).Str("notification_id", arg.ID.String()).Msg("failed to mark notification read")
	}
	return err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true, read_at = NOW()
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to mark all notifications read")
	}
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to count unread notifications")
		return 0, err
	}
	return count, nil
}
