// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

// --- Enum types for organizations ---

type OrgType string

const (
	OrgTypeHousingSociety OrgType = "housing_society"
	OrgTypeCompany        OrgType = "company"
	OrgTypeInstitution    OrgType = "institution"
)

type OrgStatus string

const (
	OrgStatusActive    OrgStatus = "active"
	OrgStatusSuspended OrgStatus = "suspended"
	OrgStatusPending   OrgStatus = "pending"
)

type OrgRole string

const (
	OrgRoleAdmin   OrgRole = "admin"
	OrgRoleManager OrgRole = "manager"
	OrgRoleMember  OrgRole = "member"
)

type MemberStatus string

const (
	MemberStatusActive   MemberStatus = "active"
	MemberStatusInactive MemberStatus = "inactive"
	MemberStatusInvited  MemberStatus = "invited"
)

type RequestPriority string

const (
	RequestPriorityLow    RequestPriority = "low"
	RequestPriorityMedium RequestPriority = "medium"
	RequestPriorityHigh   RequestPriority = "high"
	RequestPriorityUrgent RequestPriority = "urgent"
)

type RequestStatus string

const (
	RequestStatusPending    RequestStatus = "pending"
	RequestStatusAssigned   RequestStatus = "assigned"
	RequestStatusInProgress RequestStatus = "in_progress"
	RequestStatusCompleted  RequestStatus = "completed"
	RequestStatusCancelled  RequestStatus = "cancelled"
)

// --- Table models ---

type Organization struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Type         OrgType         `json:"type"`
	Address      pgtype.Text     `json:"address"`
	Postcode     pgtype.Text     `json:"postcode"`
	City         pgtype.Text     `json:"city"`
	State        pgtype.Text     `json:"state"`
	Country      string          `json:"country"`
	ContactPhone pgtype.Text     `json:"contact_phone"`
	ContactEmail pgtype.Text     `json:"contact_email"`
	LogoUrl      pgtype.Text     `json:"logo_url"`
	Settings     json.RawMessage `json:"settings"`
	Status       OrgStatus       `json:"status"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type OrganizationMember struct {
	ID       uuid.UUID    `json:"id"`
	OrgID    uuid.UUID    `json:"org_id"`
	UserID   uuid.UUID    `json:"user_id"`
	Role     OrgRole      `json:"role"`
	JoinedAt time.Time    `json:"joined_at"`
	Status   MemberStatus `json:"status"`
}

type OrganizationServiceRequest struct {
	ID                 uuid.UUID          `json:"id"`
	OrgID              uuid.UUID          `json:"org_id"`
	RequestedBy        uuid.UUID          `json:"requested_by"`
	CategoryID         uuid.UUID          `json:"category_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Priority           RequestPriority    `json:"priority"`
	Status             RequestStatus      `json:"status"`
	AssignedProviderID *uuid.UUID         `json:"assigned_provider_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

// --- Query implementations ---

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, type, address, postcode, city, state, country, contact_phone, contact_email, logo_url, settings, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, type, address, postcode, city, state, country, contact_phone, contact_email, logo_url, settings, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name         string          `json:"name"`
	Type         OrgType         `json:"type"`
	Address      pgtype.Text     `json:"address"`
	Postcode     pgtype.Text     `json:"postcode"`
	City         pgtype.Text     `json:"city"`
	State        pgtype.Text     `json:"state"`
	Country      string          `json:"country"`
	ContactPhone pgtype.Text     `json:"contact_phone"`
	ContactEmail pgtype.Text     `json:"contact_email"`
	LogoUrl      pgtype.Text     `json:"logo_url"`
	Settings     json.RawMessage `json:"settings"`
	Status       OrgStatus       `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Type,
		arg.Address,
		arg.Postcode,
		arg.City,
		arg.State,
		arg.Country,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.LogoUrl,
		arg.Settings,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.Postcode,
		&i.City,
		&i.State,
		&i.Country,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to create organization")
		return i, err
	}
	return i, nil
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, type, address, postcode, city, state, country, contact_phone, contact_email, logo_url, settings, status, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.Postcode,
		&i.City,
		&i.State,
		&i.Country,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("org_id", id.String()).Msg("organization not found")
			return i, err
		}
		log.Error().Err(err).Str("org_id", id.String()).Msg("failed to get organization by id")
		return i, err
	}
	return i, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, type, address, postcode, city, state, country, contact_phone, contact_email, logo_url, settings, status, created_at, updated_at FROM organizations
WHERE status = COALESCE($3, status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		log.Error().Err(err).Msg("failed to list organizations")
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.Postcode,
			&i.City,
			&i.State,
			&i.Country,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.LogoUrl,
			&i.Settings,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan organization row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating organization rows")
		return nil, err
	}
	return items, nil
}

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO organization_members (org_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, user_id, role, joined_at, status
`

type AddOrganizationMemberParams struct {
	OrgID  uuid.UUID    `json:"org_id"`
	UserID uuid.UUID    `json:"user_id"`
	Role   OrgRole      `json:"role"`
	Status MemberStatus `json:"status"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Status,
	)
	if err != nil {
		log.Error().Err(err).Str("org_id", arg.OrgID.String()).Str("user_id", arg.UserID.String()).Msg("failed to add organization member")
		return i, err
	}
	return i, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members WHERE org_id = $1 AND user_id = $2
`

func (q *Queries) RemoveOrganizationMember(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, orgID, userID)
	if err != nil {
		log.Error().Err(err).Str("org_id", orgID.String()).Str("user_id", userID.String()).Msg("failed to remove organization member")
	}
	return err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT om.id, om.org_id, om.user_id, om.role, om.joined_at, om.status, u.name as user_name, u.phone as user_phone, u.email as user_email
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = $1
ORDER BY om.joined_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationMembersRow struct {
	ID        uuid.UUID    `json:"id"`
	OrgID     uuid.UUID    `json:"org_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Role      OrgRole      `json:"role"`
	JoinedAt  time.Time    `json:"joined_at"`
	Status    MemberStatus `json:"status"`
	UserName  pgtype.Text  `json:"user_name"`
	UserPhone string       `json:"user_phone"`
	UserEmail pgtype.Text  `json:"user_email"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, orgID uuid.UUID, limit int32, offset int32) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, orgID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("org_id", orgID.String()).Msg("failed to list organization members")
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Status,
			&i.UserName,
			&i.UserPhone,
			&i.UserEmail,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan organization member row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating organization member rows")
		return nil, err
	}
	return items, nil
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role, status FROM organization_members WHERE org_id = $1 AND user_id = $2
`

type GetMemberRoleRow struct {
	Role   OrgRole      `json:"role"`
	Status MemberStatus `json:"status"`
}

func (q *Queries) GetMemberRole(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (GetMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, getMemberRole, orgID, userID)
	var i GetMemberRoleRow
	err := row.Scan(&i.Role, &i.Status)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("org_id", orgID.String()).Str("user_id", userID.String()).Msg("member not found")
			return i, err
		}
		log.Error().Err(err).Str("org_id", orgID.String()).Str("user_id", userID.String()).Msg("failed to get member role")
		return i, err
	}
	return i, nil
}

const createOrganizationServiceRequest = `-- name: CreateOrganizationServiceRequest :one
INSERT INTO organization_service_requests (org_id, requested_by, category_id, title, description, priority, status, scheduled_at, notes)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $8)
RETURNING id, org_id, requested_by, category_id, title, description, priority, status, assigned_provider_id, scheduled_at, completed_at, notes, created_at, updated_at
`

type CreateOrganizationServiceRequestParams struct {
	OrgID       uuid.UUID          `json:"org_id"`
	RequestedBy uuid.UUID          `json:"requested_by"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    RequestPriority    `json:"priority"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Notes       pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateOrganizationServiceRequest(ctx context.Context, arg CreateOrganizationServiceRequestParams) (OrganizationServiceRequest, error) {
	row := q.db.QueryRow(ctx, createOrganizationServiceRequest,
		arg.OrgID,
		arg.RequestedBy,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.ScheduledAt,
		arg.Notes,
	)
	var i OrganizationServiceRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestedBy,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedProviderID,
		&i.ScheduledAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("org_id", arg.OrgID.String()).Msg("failed to create organization service request")
		return i, err
	}
	return i, nil
}

const listOrganizationServiceRequests = `-- name: ListOrganizationServiceRequests :many
SELECT osr.id, osr.org_id, osr.requested_by, osr.category_id, osr.title, osr.description, osr.priority, osr.status, osr.assigned_provider_id, osr.scheduled_at, osr.completed_at, osr.notes, osr.created_at, osr.updated_at,
       u.name as requester_name, c.slug as category_slug, c.name as category_name,
       pu.name as provider_name
FROM organization_service_requests osr
JOIN users u ON u.id = osr.requested_by
JOIN categories c ON c.id = osr.category_id
LEFT JOIN users pu ON pu.id = osr.assigned_provider_id
WHERE osr.org_id = $1
  AND osr.status = COALESCE($4, osr.status)
  AND osr.priority = COALESCE($5, osr.priority)
ORDER BY osr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationServiceRequestsParams struct {
	OrgID    uuid.UUID   `json:"org_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	Priority pgtype.Text `json:"priority"`
}

type ListOrganizationServiceRequestsRow struct {
	ID                 uuid.UUID          `json:"id"`
	OrgID              uuid.UUID          `json:"org_id"`
	RequestedBy        uuid.UUID          `json:"requested_by"`
	CategoryID         uuid.UUID          `json:"category_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Priority           RequestPriority    `json:"priority"`
	Status             RequestStatus      `json:"status"`
	AssignedProviderID *uuid.UUID         `json:"assigned_provider_id"`
	ScheduledAt        pgtype.Timestamptz `json:"scheduled_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RequesterName      pgtype.Text        `json:"requester_name"`
	CategorySlug       string             `json:"category_slug"`
	CategoryName       json.RawMessage    `json:"category_name"`
	ProviderName       pgtype.Text        `json:"provider_name"`
}

func (q *Queries) ListOrganizationServiceRequests(ctx context.Context, arg ListOrganizationServiceRequestsParams) ([]ListOrganizationServiceRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationServiceRequests,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Priority,
	)
	if err != nil {
		log.Error().Err(err).Str("org_id", arg.OrgID.String()).Msg("failed to list organization service requests")
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationServiceRequestsRow{}
	for rows.Next() {
		var i ListOrganizationServiceRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestedBy,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedProviderID,
			&i.ScheduledAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterName,
			&i.CategorySlug,
			&i.CategoryName,
			&i.ProviderName,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan organization service request row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating organization service request rows")
		return nil, err
	}
	return items, nil
}

const updateOrganizationServiceRequestStatus = `-- name: UpdateOrganizationServiceRequestStatus :one
UPDATE organization_service_requests
SET status = $2
WHERE id = $1
RETURNING id, org_id, requested_by, category_id, title, description, priority, status, assigned_provider_id, scheduled_at, completed_at, notes, created_at, updated_at
`

func (q *Queries) UpdateOrganizationServiceRequestStatus(ctx context.Context, id uuid.UUID, status RequestStatus) (OrganizationServiceRequest, error) {
	row := q.db.QueryRow(ctx, updateOrganizationServiceRequestStatus, id, status)
	var i OrganizationServiceRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestedBy,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedProviderID,
		&i.ScheduledAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("request_id", id.String()).Msg("failed to update organization service request status")
		return i, err
	}
	return i, nil
}

const assignOrganizationServiceRequestProvider = `-- name: AssignOrganizationServiceRequestProvider :one
UPDATE organization_service_requests
SET assigned_provider_id = $2, status = 'assigned'
WHERE id = $1
RETURNING id, org_id, requested_by, category_id, title, description, priority, status, assigned_provider_id, scheduled_at, completed_at, notes, created_at, updated_at
`

func (q *Queries) AssignOrganizationServiceRequestProvider(ctx context.Context, id uuid.UUID, providerID uuid.UUID) (OrganizationServiceRequest, error) {
	row := q.db.QueryRow(ctx, assignOrganizationServiceRequestProvider, id, providerID)
	var i OrganizationServiceRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestedBy,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedProviderID,
		&i.ScheduledAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("request_id", id.String()).Msg("failed to assign provider to organization service request")
		return i, err
	}
	return i, nil
}

const countOrganizationServiceRequestsByStatus = `-- name: CountOrganizationServiceRequestsByStatus :one
SELECT COUNT(*) FROM organization_service_requests WHERE org_id = $1 AND status = $2
`

func (q *Queries) CountOrganizationServiceRequestsByStatus(ctx context.Context, orgID uuid.UUID, status RequestStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationServiceRequestsByStatus, orgID, status)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("org_id", orgID.String()).Msg("failed to count organization service requests by status")
		return 0, err
	}
	return count, nil
}

const countOrganizationMembers = `-- name: CountOrganizationMembers :one
SELECT COUNT(*) FROM organization_members WHERE org_id = $1 AND status = 'active'
`

func (q *Queries) CountOrganizationMembers(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, orgID)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("org_id", orgID.String()).Msg("failed to count organization members")
		return 0, err
	}
	return count, nil
}
