// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (phone, code, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '5 minutes')
RETURNING id, phone, code, attempts, max_attempts, expires_at, verified_at, created_at
`

type CreateOTPParams struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.Phone, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("phone", arg.Phone).Msg("failed to create OTP")
		return i, err
	}
	return i, nil
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, phone, code, attempts, max_attempts, expires_at, verified_at, created_at FROM otp_codes
WHERE phone = $1
  AND code = $2
  AND verified_at IS NULL
  AND attempts < max_attempts
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetValidOTPParams struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.Phone, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("phone", arg.Phone).Msg("no valid OTP found")
			return i, err
		}
		log.Error().Err(err).Str("phone", arg.Phone).Msg("failed to get valid OTP")
		return i, err
	}
	return i, nil
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	if err != nil {
		log.Error().Err(err).Str("otp_id", id.String()).Msg("failed to increment OTP attempts")
	}
	return err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_codes SET verified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	if err != nil {
		log.Error().Err(err).Str("otp_id", id.String()).Msg("failed to mark OTP verified")
	}
	return err
}

const cleanExpiredOTPs = `-- name: CleanExpiredOTPs :exec
DELETE FROM otp_codes WHERE expires_at < NOW() - INTERVAL '1 hour'
`

func (q *Queries) CleanExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredOTPs)
	if err != nil {
		log.Error().Err(err).Msg("failed to clean expired OTPs")
	}
	return err
}

const countRecentOTPs = `-- name: CountRecentOTPs :one
SELECT COUNT(*) FROM otp_codes
WHERE phone = $1 AND created_at > NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountRecentOTPs(ctx context.Context, phone string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPs, phone)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("phone", phone).Msg("failed to count recent OTPs")
		return 0, err
	}
	return count, nil
}
