// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const addPoints = `-- name: AddPoints :one
INSERT INTO points_ledger (user_id, points, reason, reference_id, reference_type, balance_after)
VALUES ($1, $2, $3, $4, $5,
    (SELECT COALESCE(SUM(points), 0) + $2 FROM points_ledger WHERE user_id = $1))
RETURNING id, user_id, points, reason, reference_id, reference_type, balance_after, created_at
`

type AddPointsParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Points        int32       `json:"points"`
	Reason        string      `json:"reason"`
	ReferenceID   *uuid.UUID  `json:"reference_id"`
	ReferenceType pgtype.Text `json:"reference_type"`
}

func (q *Queries) AddPoints(ctx context.Context, arg AddPointsParams) (PointsLedger, error) {
	row := q.db.QueryRow(ctx, addPoints,
		arg.UserID,
		arg.Points,
		arg.Reason,
		arg.ReferenceID,
		arg.ReferenceType,
	)
	var i PointsLedger
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Points,
		&i.Reason,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to add points")
		return i, err
	}
	return i, nil
}

const getPointsBalance = `-- name: GetPointsBalance :one
SELECT COALESCE(SUM(points), 0)::INTEGER as balance
FROM points_ledger
WHERE user_id = $1
`

func (q *Queries) GetPointsBalance(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPointsBalance, userID)
	var balance int32
	err := row.Scan(&balance)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to get points balance")
		return 0, err
	}
	return balance, nil
}

const listPointsHistory = `-- name: ListPointsHistory :many
SELECT id, user_id, points, reason, reference_id, reference_type, balance_after, created_at FROM points_ledger
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPointsHistoryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPointsHistory(ctx context.Context, arg ListPointsHistoryParams) ([]PointsLedger, error) {
	rows, err := q.db.Query(ctx, listPointsHistory,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to list points history")
		return nil, err
	}
	defer rows.Close()
	items := []PointsLedger{}
	for rows.Next() {
		var i PointsLedger
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Points,
			&i.Reason,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan points ledger row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating points ledger rows")
		return nil, err
	}
	return items, nil
}
