// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const addProviderCategory = `-- name: AddProviderCategory :exec
INSERT INTO provider_categories (provider_id, category_id, years_experience, is_primary)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, category_id) DO UPDATE SET years_experience = $3, is_primary = $4
`

type AddProviderCategoryParams struct {
	ProviderID      uuid.UUID   `json:"provider_id"`
	CategoryID      uuid.UUID   `json:"category_id"`
	YearsExperience pgtype.Int4 `json:"years_experience"`
	IsPrimary       bool        `json:"is_primary"`
}

func (q *Queries) AddProviderCategory(ctx context.Context, arg AddProviderCategoryParams) error {
	_, err := q.db.Exec(ctx, addProviderCategory,
		arg.ProviderID,
		arg.CategoryID,
		arg.YearsExperience,
		arg.IsPrimary,
	)
	if err != nil {
		log.Error().Err(err).
			Str("provider_id", arg.ProviderID.String()).
			Str("category_id", arg.CategoryID.String()).
			Msg("failed to add provider category")
		return err
	}
	return nil
}

const listProviderCategories = `-- name: ListProviderCategories :many
SELECT provider_id, category_id, years_experience, is_primary, created_at FROM provider_categories WHERE provider_id = $1
`

func (q *Queries) ListProviderCategories(ctx context.Context, providerID uuid.UUID) ([]ProviderCategory, error) {
	rows, err := q.db.Query(ctx, listProviderCategories, providerID)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to list provider categories")
		return nil, err
	}
	defer rows.Close()

	items := []ProviderCategory{}
	for rows.Next() {
		var i ProviderCategory
		if err := rows.Scan(
			&i.ProviderID,
			&i.CategoryID,
			&i.YearsExperience,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan provider category row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProviderCategory = `-- name: RemoveProviderCategory :exec
DELETE FROM provider_categories WHERE provider_id = $1 AND category_id = $2
`

func (q *Queries) RemoveProviderCategory(ctx context.Context, providerID uuid.UUID, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeProviderCategory, providerID, categoryID)
	if err != nil {
		log.Error().Err(err).
			Str("provider_id", providerID.String()).
			Str("category_id", categoryID.String()).
			Msg("failed to remove provider category")
		return err
	}
	return nil
}
