// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createProviderProfile = `-- name: CreateProviderProfile :one
INSERT INTO provider_profiles (user_id, business_name, description, skills, service_radius_km, postcode, location)
VALUES ($1, $2, $3, $4, $5, $6, ST_MakePoint($7, $8)::geography)
RETURNING id, user_id, business_name, description, skills, service_radius_km, postcode, location, trust_score, level, verification_status, subscription_tier, total_jobs_completed, total_reviews, avg_response_time_minutes, availability_schedule, documents, bank_account_id, wallet_balance, is_available, created_at, updated_at
`

type CreateProviderProfileParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	BusinessName    pgtype.Text    `json:"business_name"`
	Description     pgtype.Text    `json:"description"`
	Skills          []string       `json:"skills"`
	ServiceRadiusKM pgtype.Numeric `json:"service_radius_km"`
	Postcode        pgtype.Text    `json:"postcode"`
	Longitude       float64        `json:"longitude"`
	Latitude        float64        `json:"latitude"`
}

func (q *Queries) CreateProviderProfile(ctx context.Context, arg CreateProviderProfileParams) (ProviderProfile, error) {
	row := q.db.QueryRow(ctx, createProviderProfile,
		arg.UserID,
		arg.BusinessName,
		arg.Description,
		arg.Skills,
		arg.ServiceRadiusKM,
		arg.Postcode,
		arg.Longitude,
		arg.Latitude,
	)
	var i ProviderProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Description,
		&i.Skills,
		&i.ServiceRadiusKM,
		&i.Postcode,
		&i.Location,
		&i.TrustScore,
		&i.Level,
		&i.VerificationStatus,
		&i.SubscriptionTier,
		&i.TotalJobsCompleted,
		&i.TotalReviews,
		&i.AvgResponseTimeMinutes,
		&i.AvailabilitySchedule,
		&i.Documents,
		&i.BankAccountID,
		&i.WalletBalance,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to create provider profile")
		return i, err
	}
	return i, nil
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT p.id, p.user_id, p.business_name, p.description, p.skills, p.service_radius_km, p.postcode, p.location, p.trust_score, p.level, p.verification_status, p.subscription_tier, p.total_jobs_completed, p.total_reviews, p.avg_response_time_minutes, p.availability_schedule, p.documents, p.bank_account_id, p.wallet_balance, p.is_available, p.created_at, p.updated_at,
       u.name as user_name, u.phone as user_phone, u.email as user_email, u.avatar_url as user_avatar
FROM provider_profiles p
JOIN users u ON u.id = p.user_id
WHERE p.id = $1
`

type GetProviderByIDRow struct {
	ProviderProfile
	UserName   pgtype.Text `json:"user_name"`
	UserPhone  string      `json:"user_phone"`
	UserEmail  pgtype.Text `json:"user_email"`
	UserAvatar pgtype.Text `json:"user_avatar"`
}

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (GetProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i GetProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Description,
		&i.Skills,
		&i.ServiceRadiusKM,
		&i.Postcode,
		&i.Location,
		&i.TrustScore,
		&i.Level,
		&i.VerificationStatus,
		&i.SubscriptionTier,
		&i.TotalJobsCompleted,
		&i.TotalReviews,
		&i.AvgResponseTimeMinutes,
		&i.AvailabilitySchedule,
		&i.Documents,
		&i.BankAccountID,
		&i.WalletBalance,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPhone,
		&i.UserEmail,
		&i.UserAvatar,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("provider_id", id.String()).Msg("provider not found")
			return i, err
		}
		log.Error().Err(err).Str("provider_id", id.String()).Msg("failed to get provider by id")
		return i, err
	}
	return i, nil
}

const getProviderByUserID = `-- name: GetProviderByUserID :one
SELECT p.id, p.user_id, p.business_name, p.description, p.skills, p.service_radius_km, p.postcode, p.location, p.trust_score, p.level, p.verification_status, p.subscription_tier, p.total_jobs_completed, p.total_reviews, p.avg_response_time_minutes, p.availability_schedule, p.documents, p.bank_account_id, p.wallet_balance, p.is_available, p.created_at, p.updated_at,
       u.name as user_name, u.phone as user_phone, u.email as user_email, u.avatar_url as user_avatar
FROM provider_profiles p
JOIN users u ON u.id = p.user_id
WHERE p.user_id = $1
`

type GetProviderByUserIDRow struct {
	ProviderProfile
	UserName   pgtype.Text `json:"user_name"`
	UserPhone  string      `json:"user_phone"`
	UserEmail  pgtype.Text `json:"user_email"`
	UserAvatar pgtype.Text `json:"user_avatar"`
}

func (q *Queries) GetProviderByUserID(ctx context.Context, userID uuid.UUID) (GetProviderByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByUserID, userID)
	var i GetProviderByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Description,
		&i.Skills,
		&i.ServiceRadiusKM,
		&i.Postcode,
		&i.Location,
		&i.TrustScore,
		&i.Level,
		&i.VerificationStatus,
		&i.SubscriptionTier,
		&i.TotalJobsCompleted,
		&i.TotalReviews,
		&i.AvgResponseTimeMinutes,
		&i.AvailabilitySchedule,
		&i.Documents,
		&i.BankAccountID,
		&i.WalletBalance,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPhone,
		&i.UserEmail,
		&i.UserAvatar,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("user_id", userID.String()).Msg("provider not found by user id")
			return i, err
		}
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to get provider by user id")
		return i, err
	}
	return i, nil
}

const searchProvidersByLocation = `-- name: SearchProvidersByLocation :many
SELECT p.id, p.user_id, p.business_name, p.description, p.skills, p.service_radius_km, p.postcode, p.location, p.trust_score, p.level, p.verification_status, p.subscription_tier, p.total_jobs_completed, p.total_reviews, p.avg_response_time_minutes, p.availability_schedule, p.documents, p.bank_account_id, p.wallet_balance, p.is_available, p.created_at, p.updated_at,
       u.name as user_name, u.phone as user_phone, u.avatar_url as user_avatar,
       ST_Distance(p.location, ST_MakePoint($1, $2)::geography) as distance_meters
FROM provider_profiles p
JOIN users u ON u.id = p.user_id
WHERE ST_DWithin(p.location, ST_MakePoint($1, $2)::geography, $3)
  AND p.is_available = true
  AND p.verification_status = 'verified'
  AND u.is_active = true
ORDER BY p.trust_score DESC, distance_meters ASC
LIMIT $4 OFFSET $5
`

type SearchProvidersByLocationParams struct {
	Longitude    float64 `json:"longitude"`
	Latitude     float64 `json:"latitude"`
	RadiusMeters float64 `json:"radius_meters"`
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
}

type SearchProvidersByLocationRow struct {
	ProviderProfile
	UserName       pgtype.Text `json:"user_name"`
	UserPhone      string      `json:"user_phone"`
	UserAvatar     pgtype.Text `json:"user_avatar"`
	DistanceMeters float64     `json:"distance_meters"`
}

func (q *Queries) SearchProvidersByLocation(ctx context.Context, arg SearchProvidersByLocationParams) ([]SearchProvidersByLocationRow, error) {
	rows, err := q.db.Query(ctx, searchProvidersByLocation,
		arg.Longitude,
		arg.Latitude,
		arg.RadiusMeters,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to search providers by location")
		return nil, err
	}
	defer rows.Close()
	items := []SearchProvidersByLocationRow{}
	for rows.Next() {
		var i SearchProvidersByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessName,
			&i.Description,
			&i.Skills,
			&i.ServiceRadiusKM,
			&i.Postcode,
			&i.Location,
			&i.TrustScore,
			&i.Level,
			&i.VerificationStatus,
			&i.SubscriptionTier,
			&i.TotalJobsCompleted,
			&i.TotalReviews,
			&i.AvgResponseTimeMinutes,
			&i.AvailabilitySchedule,
			&i.Documents,
			&i.BankAccountID,
			&i.WalletBalance,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
			&i.UserAvatar,
			&i.DistanceMeters,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan provider location row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating provider location rows")
		return nil, err
	}
	return items, nil
}

const searchProvidersByPostcode = `-- name: SearchProvidersByPostcode :many
SELECT p.id, p.user_id, p.business_name, p.description, p.skills, p.service_radius_km, p.postcode, p.location, p.trust_score, p.level, p.verification_status, p.subscription_tier, p.total_jobs_completed, p.total_reviews, p.avg_response_time_minutes, p.availability_schedule, p.documents, p.bank_account_id, p.wallet_balance, p.is_available, p.created_at, p.updated_at,
       u.name as user_name, u.phone as user_phone, u.avatar_url as user_avatar
FROM provider_profiles p
JOIN users u ON u.id = p.user_id
WHERE p.postcode = $1
  AND p.is_available = true
  AND u.is_active = true
ORDER BY p.trust_score DESC
LIMIT $2 OFFSET $3
`

type SearchProvidersByPostcodeParams struct {
	Postcode string `json:"postcode"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type SearchProvidersByPostcodeRow struct {
	ProviderProfile
	UserName   pgtype.Text `json:"user_name"`
	UserPhone  string      `json:"user_phone"`
	UserAvatar pgtype.Text `json:"user_avatar"`
}

func (q *Queries) SearchProvidersByPostcode(ctx context.Context, arg SearchProvidersByPostcodeParams) ([]SearchProvidersByPostcodeRow, error) {
	rows, err := q.db.Query(ctx, searchProvidersByPostcode,
		arg.Postcode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to search providers by postcode")
		return nil, err
	}
	defer rows.Close()
	items := []SearchProvidersByPostcodeRow{}
	for rows.Next() {
		var i SearchProvidersByPostcodeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessName,
			&i.Description,
			&i.Skills,
			&i.ServiceRadiusKM,
			&i.Postcode,
			&i.Location,
			&i.TrustScore,
			&i.Level,
			&i.VerificationStatus,
			&i.SubscriptionTier,
			&i.TotalJobsCompleted,
			&i.TotalReviews,
			&i.AvgResponseTimeMinutes,
			&i.AvailabilitySchedule,
			&i.Documents,
			&i.BankAccountID,
			&i.WalletBalance,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
			&i.UserAvatar,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan provider postcode row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating provider postcode rows")
		return nil, err
	}
	return items, nil
}

const searchProvidersBySkill = `-- name: SearchProvidersBySkill :many
SELECT p.id, p.user_id, p.business_name, p.description, p.skills, p.service_radius_km, p.postcode, p.location, p.trust_score, p.level, p.verification_status, p.subscription_tier, p.total_jobs_completed, p.total_reviews, p.avg_response_time_minutes, p.availability_schedule, p.documents, p.bank_account_id, p.wallet_balance, p.is_available, p.created_at, p.updated_at,
       u.name as user_name, u.phone as user_phone, u.avatar_url as user_avatar
FROM provider_profiles p
JOIN users u ON u.id = p.user_id
WHERE p.skills @> $1::text[]
  AND p.is_available = true
  AND u.is_active = true
ORDER BY p.trust_score DESC
LIMIT $2 OFFSET $3
`

type SearchProvidersBySkillParams struct {
	Skills []string `json:"skills"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

type SearchProvidersBySkillRow struct {
	ProviderProfile
	UserName   pgtype.Text `json:"user_name"`
	UserPhone  string      `json:"user_phone"`
	UserAvatar pgtype.Text `json:"user_avatar"`
}

func (q *Queries) SearchProvidersBySkill(ctx context.Context, arg SearchProvidersBySkillParams) ([]SearchProvidersBySkillRow, error) {
	rows, err := q.db.Query(ctx, searchProvidersBySkill,
		arg.Skills,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to search providers by skill")
		return nil, err
	}
	defer rows.Close()
	items := []SearchProvidersBySkillRow{}
	for rows.Next() {
		var i SearchProvidersBySkillRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessName,
			&i.Description,
			&i.Skills,
			&i.ServiceRadiusKM,
			&i.Postcode,
			&i.Location,
			&i.TrustScore,
			&i.Level,
			&i.VerificationStatus,
			&i.SubscriptionTier,
			&i.TotalJobsCompleted,
			&i.TotalReviews,
			&i.AvgResponseTimeMinutes,
			&i.AvailabilitySchedule,
			&i.Documents,
			&i.BankAccountID,
			&i.WalletBalance,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
			&i.UserAvatar,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan provider skill row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating provider skill rows")
		return nil, err
	}
	return items, nil
}

const updateProviderProfile = `-- name: UpdateProviderProfile :one
UPDATE provider_profiles
SET business_name = COALESCE($2, business_name),
    description = COALESCE($3, description),
    skills = COALESCE($4, skills),
    service_radius_km = COALESCE($5, service_radius_km),
    postcode = COALESCE($6, postcode),
    is_available = COALESCE($7, is_available)
WHERE id = $1
RETURNING id, user_id, business_name, description, skills, service_radius_km, postcode, location, trust_score, level, verification_status, subscription_tier, total_jobs_completed, total_reviews, avg_response_time_minutes, availability_schedule, documents, bank_account_id, wallet_balance, is_available, created_at, updated_at
`

type UpdateProviderProfileParams struct {
	ID              uuid.UUID      `json:"id"`
	BusinessName    pgtype.Text    `json:"business_name"`
	Description     pgtype.Text    `json:"description"`
	Skills          []string       `json:"skills"`
	ServiceRadiusKM pgtype.Numeric `json:"service_radius_km"`
	Postcode        pgtype.Text    `json:"postcode"`
	IsAvailable     pgtype.Bool    `json:"is_available"`
}

func (q *Queries) UpdateProviderProfile(ctx context.Context, arg UpdateProviderProfileParams) (ProviderProfile, error) {
	row := q.db.QueryRow(ctx, updateProviderProfile,
		arg.ID,
		arg.BusinessName,
		arg.Description,
		arg.Skills,
		arg.ServiceRadiusKM,
		arg.Postcode,
		arg.IsAvailable,
	)
	var i ProviderProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Description,
		&i.Skills,
		&i.ServiceRadiusKM,
		&i.Postcode,
		&i.Location,
		&i.TrustScore,
		&i.Level,
		&i.VerificationStatus,
		&i.SubscriptionTier,
		&i.TotalJobsCompleted,
		&i.TotalReviews,
		&i.AvgResponseTimeMinutes,
		&i.AvailabilitySchedule,
		&i.Documents,
		&i.BankAccountID,
		&i.WalletBalance,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("provider_id", arg.ID.String()).Msg("failed to update provider profile")
		return i, err
	}
	return i, nil
}

const updateTrustScore = `-- name: UpdateTrustScore :exec
UPDATE provider_profiles
SET trust_score = $2,
    level = $3
WHERE id = $1
`

type UpdateTrustScoreParams struct {
	ID         uuid.UUID      `json:"id"`
	TrustScore pgtype.Numeric `json:"trust_score"`
	Level      ProviderLevel  `json:"level"`
}

func (q *Queries) UpdateTrustScore(ctx context.Context, arg UpdateTrustScoreParams) error {
	_, err := q.db.Exec(ctx, updateTrustScore, arg.ID, arg.TrustScore, arg.Level)
	if err != nil {
		log.Error().Err(err).Str("provider_id", arg.ID.String()).Msg("failed to update trust score")
	}
	return err
}

const incrementJobsCompleted = `-- name: IncrementJobsCompleted :exec
UPDATE provider_profiles
SET total_jobs_completed = total_jobs_completed + 1,
    total_reviews = total_reviews + 1
WHERE user_id = $1
`

func (q *Queries) IncrementJobsCompleted(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementJobsCompleted, userID)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to increment jobs completed")
	}
	return err
}

const updateVerificationStatus = `-- name: UpdateVerificationStatus :exec
UPDATE provider_profiles
SET verification_status = $2
WHERE id = $1
`

type UpdateVerificationStatusParams struct {
	ID                 uuid.UUID          `json:"id"`
	VerificationStatus VerificationStatus `json:"verification_status"`
}

func (q *Queries) UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateVerificationStatus, arg.ID, arg.VerificationStatus)
	if err != nil {
		log.Error().Err(err).Str("provider_id", arg.ID.String()).Msg("failed to update verification status")
	}
	return err
}
