// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const setProviderAvailability = `-- name: SetProviderAvailability :exec
INSERT INTO provider_availability (provider_id, day_of_week, start_time, end_time, is_available)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider_id, day_of_week, start_time) DO UPDATE SET end_time = $4, is_available = $5
`

type SetProviderAvailabilityParams struct {
	ProviderID  uuid.UUID   `json:"provider_id"`
	DayOfWeek   int16       `json:"day_of_week"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	IsAvailable bool        `json:"is_available"`
}

func (q *Queries) SetProviderAvailability(ctx context.Context, arg SetProviderAvailabilityParams) error {
	_, err := q.db.Exec(ctx, setProviderAvailability,
		arg.ProviderID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.IsAvailable,
	)
	if err != nil {
		log.Error().Err(err).
			Str("provider_id", arg.ProviderID.String()).
			Int("day_of_week", int(arg.DayOfWeek)).
			Msg("failed to set provider availability")
		return err
	}
	return nil
}

const getProviderAvailability = `-- name: GetProviderAvailability :many
SELECT id, provider_id, day_of_week, start_time, end_time, is_available, created_at FROM provider_availability WHERE provider_id = $1 ORDER BY day_of_week
`

func (q *Queries) GetProviderAvailability(ctx context.Context, providerID uuid.UUID) ([]ProviderAvailability, error) {
	rows, err := q.db.Query(ctx, getProviderAvailability, providerID)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get provider availability")
		return nil, err
	}
	defer rows.Close()

	items := []ProviderAvailability{}
	for rows.Next() {
		var i ProviderAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsAvailable,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan provider availability row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
