// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

// RecurringSchedule represents a row in the recurring_schedules table.
type RecurringSchedule struct {
	ID               uuid.UUID           `json:"id"`
	CustomerID       uuid.UUID           `json:"customer_id"`
	ProviderID       uuid.UUID           `json:"provider_id"`
	CategoryID       uuid.UUID           `json:"category_id"`
	Title            string              `json:"title"`
	Description      pgtype.Text         `json:"description"`
	Frequency        RecurrenceFrequency `json:"frequency"`
	DayOfWeek        pgtype.Int4         `json:"day_of_week"`
	DayOfMonth       pgtype.Int4         `json:"day_of_month"`
	PreferredTime    pgtype.Time         `json:"preferred_time"`
	Amount           pgtype.Numeric      `json:"amount"`
	Currency         string              `json:"currency"`
	Status           ScheduleStatus      `json:"status"`
	NextOccurrence   pgtype.Timestamptz  `json:"next_occurrence"`
	LastOccurrence   pgtype.Timestamptz  `json:"last_occurrence"`
	TotalOccurrences int32               `json:"total_occurrences"`
	MaxOccurrences   pgtype.Int4         `json:"max_occurrences"`
	CreatedAt        time.Time           `json:"created_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO recurring_schedules (customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'active', $12)
RETURNING id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at
`

type CreateScheduleParams struct {
	CustomerID     uuid.UUID           `json:"customer_id"`
	ProviderID     uuid.UUID           `json:"provider_id"`
	CategoryID     uuid.UUID           `json:"category_id"`
	Title          string              `json:"title"`
	Description    pgtype.Text         `json:"description"`
	Frequency      RecurrenceFrequency `json:"frequency"`
	DayOfWeek      pgtype.Int4         `json:"day_of_week"`
	DayOfMonth     pgtype.Int4         `json:"day_of_month"`
	PreferredTime  pgtype.Time         `json:"preferred_time"`
	Amount         pgtype.Numeric      `json:"amount"`
	Currency       string              `json:"currency"`
	NextOccurrence pgtype.Timestamptz  `json:"next_occurrence"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (RecurringSchedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.CustomerID,
		arg.ProviderID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Frequency,
		arg.DayOfWeek,
		arg.DayOfMonth,
		arg.PreferredTime,
		arg.Amount,
		arg.Currency,
		arg.NextOccurrence,
	)
	var i RecurringSchedule
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.PreferredTime,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.NextOccurrence,
		&i.LastOccurrence,
		&i.TotalOccurrences,
		&i.MaxOccurrences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("customer_id", arg.CustomerID.String()).Msg("failed to create recurring schedule")
		return i, err
	}
	return i, nil
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at FROM recurring_schedules WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id uuid.UUID) (RecurringSchedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i RecurringSchedule
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.PreferredTime,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.NextOccurrence,
		&i.LastOccurrence,
		&i.TotalOccurrences,
		&i.MaxOccurrences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("schedule_id", id.String()).Msg("recurring schedule not found")
			return i, err
		}
		log.Error().Err(err).Str("schedule_id", id.String()).Msg("failed to get recurring schedule by id")
		return i, err
	}
	return i, nil
}

const listSchedulesByCustomer = `-- name: ListSchedulesByCustomer :many
SELECT id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at FROM recurring_schedules
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListSchedulesByCustomer(ctx context.Context, customerID uuid.UUID, limit int32, offset int32) ([]RecurringSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByCustomer, customerID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("customer_id", customerID.String()).Msg("failed to list schedules by customer")
		return nil, err
	}
	defer rows.Close()

	items := []RecurringSchedule{}
	for rows.Next() {
		var i RecurringSchedule
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.DayOfWeek,
			&i.DayOfMonth,
			&i.PreferredTime,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.NextOccurrence,
			&i.LastOccurrence,
			&i.TotalOccurrences,
			&i.MaxOccurrences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan recurring schedule row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByProvider = `-- name: ListSchedulesByProvider :many
SELECT id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at FROM recurring_schedules
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListSchedulesByProvider(ctx context.Context, providerID uuid.UUID, limit int32, offset int32) ([]RecurringSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByProvider, providerID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to list schedules by provider")
		return nil, err
	}
	defer rows.Close()

	items := []RecurringSchedule{}
	for rows.Next() {
		var i RecurringSchedule
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.DayOfWeek,
			&i.DayOfMonth,
			&i.PreferredTime,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.NextOccurrence,
			&i.LastOccurrence,
			&i.TotalOccurrences,
			&i.MaxOccurrences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan recurring schedule row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleStatus = `-- name: UpdateScheduleStatus :one
UPDATE recurring_schedules
SET status = $2
WHERE id = $1
RETURNING id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at
`

func (q *Queries) UpdateScheduleStatus(ctx context.Context, id uuid.UUID, status ScheduleStatus) (RecurringSchedule, error) {
	row := q.db.QueryRow(ctx, updateScheduleStatus, id, status)
	var i RecurringSchedule
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.PreferredTime,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.NextOccurrence,
		&i.LastOccurrence,
		&i.TotalOccurrences,
		&i.MaxOccurrences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("schedule_id", id.String()).Msg("failed to update schedule status")
		return i, err
	}
	return i, nil
}

const updateNextOccurrence = `-- name: UpdateNextOccurrence :exec
UPDATE recurring_schedules
SET next_occurrence = $2,
    last_occurrence = $3,
    total_occurrences = total_occurrences + 1
WHERE id = $1
`

func (q *Queries) UpdateNextOccurrence(ctx context.Context, id uuid.UUID, nextOccurrence pgtype.Timestamptz, lastOccurrence pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateNextOccurrence, id, nextOccurrence, lastOccurrence)
	if err != nil {
		log.Error().Err(err).Str("schedule_id", id.String()).Msg("failed to update next occurrence")
		return err
	}
	return nil
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, customer_id, provider_id, category_id, title, description, frequency, day_of_week, day_of_month, preferred_time, amount, currency, status, next_occurrence, last_occurrence, total_occurrences, max_occurrences, created_at, updated_at FROM recurring_schedules
WHERE next_occurrence <= NOW()
  AND status = 'active'
ORDER BY next_occurrence ASC
LIMIT $1
`

func (q *Queries) ListDueSchedules(ctx context.Context, limit int32) ([]RecurringSchedule, error) {
	rows, err := q.db.Query(ctx, listDueSchedules, limit)
	if err != nil {
		log.Error().Err(err).Msg("failed to list due schedules")
		return nil, err
	}
	defer rows.Close()

	items := []RecurringSchedule{}
	for rows.Next() {
		var i RecurringSchedule
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.DayOfWeek,
			&i.DayOfMonth,
			&i.PreferredTime,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.NextOccurrence,
			&i.LastOccurrence,
			&i.TotalOccurrences,
			&i.MaxOccurrences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan due schedule row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
