// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (job_id, reviewer_id, reviewee_id, rating, comment, language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, reviewer_id, reviewee_id, rating, comment, language, photos, moderation_status, is_public, response, responded_at, created_at, updated_at
`

type CreateReviewParams struct {
	JobID      uuid.UUID   `json:"job_id"`
	ReviewerID uuid.UUID   `json:"reviewer_id"`
	RevieweeID uuid.UUID   `json:"reviewee_id"`
	Rating     int16       `json:"rating"`
	Comment    pgtype.Text `json:"comment"`
	Language   pgtype.Text `json:"language"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.JobID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.Rating,
		arg.Comment,
		arg.Language,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Comment,
		&i.Language,
		&i.Photos,
		&i.ModerationStatus,
		&i.IsPublic,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to create review")
		return i, err
	}
	return i, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT r.id, r.job_id, r.reviewer_id, r.reviewee_id, r.rating, r.comment, r.language, r.photos, r.moderation_status, r.is_public, r.response, r.responded_at, r.created_at, r.updated_at,
       ru.name as reviewer_name, eu.name as reviewee_name
FROM reviews r
JOIN users ru ON ru.id = r.reviewer_id
JOIN users eu ON eu.id = r.reviewee_id
WHERE r.id = $1
`

type GetReviewByIDRow struct {
	Review
	ReviewerName pgtype.Text `json:"reviewer_name"`
	RevieweeName pgtype.Text `json:"reviewee_name"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Comment,
		&i.Language,
		&i.Photos,
		&i.ModerationStatus,
		&i.IsPublic,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerName,
		&i.RevieweeName,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("review_id", id.String()).Msg("review not found")
			return i, err
		}
		log.Error().Err(err).Str("review_id", id.String()).Msg("failed to get review by id")
		return i, err
	}
	return i, nil
}

const listReviewsByProvider = `-- name: ListReviewsByProvider :many
SELECT r.id, r.job_id, r.reviewer_id, r.reviewee_id, r.rating, r.comment, r.language, r.photos, r.moderation_status, r.is_public, r.response, r.responded_at, r.created_at, r.updated_at,
       u.name as reviewer_name, j.title as job_title
FROM reviews r
JOIN users u ON u.id = r.reviewer_id
JOIN jobs j ON j.id = r.job_id
WHERE r.reviewee_id = $1
  AND r.moderation_status = 'approved'
  AND r.is_public = true
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByProviderParams struct {
	RevieweeID uuid.UUID `json:"reviewee_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListReviewsByProviderRow struct {
	Review
	ReviewerName pgtype.Text `json:"reviewer_name"`
	JobTitle     string      `json:"job_title"`
}

func (q *Queries) ListReviewsByProvider(ctx context.Context, arg ListReviewsByProviderParams) ([]ListReviewsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByProvider,
		arg.RevieweeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("reviewee_id", arg.RevieweeID.String()).Msg("failed to list reviews by provider")
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByProviderRow{}
	for rows.Next() {
		var i ListReviewsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ReviewerID,
			&i.RevieweeID,
			&i.Rating,
			&i.Comment,
			&i.Language,
			&i.Photos,
			&i.ModerationStatus,
			&i.IsPublic,
			&i.Response,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerName,
			&i.JobTitle,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan review row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating review rows")
		return nil, err
	}
	return items, nil
}

const getProviderAvgRating = `-- name: GetProviderAvgRating :one
SELECT COALESCE(AVG(rating)::DECIMAL(3,2), 0) as avg_rating, COUNT(*) as total_reviews
FROM reviews
WHERE reviewee_id = $1
  AND moderation_status = 'approved'
`

type GetProviderAvgRatingRow struct {
	AvgRating    pgtype.Numeric `json:"avg_rating"`
	TotalReviews int64          `json:"total_reviews"`
}

func (q *Queries) GetProviderAvgRating(ctx context.Context, revieweeID uuid.UUID) (GetProviderAvgRatingRow, error) {
	row := q.db.QueryRow(ctx, getProviderAvgRating, revieweeID)
	var i GetProviderAvgRatingRow
	err := row.Scan(&i.AvgRating, &i.TotalReviews)
	if err != nil {
		log.Error().Err(err).Str("reviewee_id", revieweeID.String()).Msg("failed to get provider avg rating")
		return i, err
	}
	return i, nil
}

const respondToReview = `-- name: RespondToReview :one
UPDATE reviews SET response = $2, responded_at = NOW()
WHERE id = $1
RETURNING id, job_id, reviewer_id, reviewee_id, rating, comment, language, photos, moderation_status, is_public, response, responded_at, created_at, updated_at
`

type RespondToReviewParams struct {
	ID       uuid.UUID `json:"id"`
	Response string    `json:"response"`
}

func (q *Queries) RespondToReview(ctx context.Context, arg RespondToReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, respondToReview, arg.ID, arg.Response)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Comment,
		&i.Language,
		&i.Photos,
		&i.ModerationStatus,
		&i.IsPublic,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("review_id", arg.ID.String()).Msg("failed to respond to review")
		return i, err
	}
	return i, nil
}

const moderateReview = `-- name: ModerateReview :exec
UPDATE reviews SET moderation_status = $2
WHERE id = $1
`

type ModerateReviewParams struct {
	ID               uuid.UUID        `json:"id"`
	ModerationStatus ModerationStatus `json:"moderation_status"`
}

func (q *Queries) ModerateReview(ctx context.Context, arg ModerateReviewParams) error {
	_, err := q.db.Exec(ctx, moderateReview, arg.ID, arg.ModerationStatus)
	if err != nil {
		log.Error().Err(err).Str("review_id", arg.ID.String()).Msg("failed to moderate review")
	}
	return err
}
