// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (provider_id, name, description, postcodes, frequency, day_of_week, max_stops, price_per_stop, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, provider_id, name, description, postcodes, frequency, day_of_week, max_stops, current_stops, price_per_stop, currency, is_active, created_at, updated_at
`

type CreateRouteParams struct {
	ProviderID   uuid.UUID      `json:"provider_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	Postcodes    []string       `json:"postcodes"`
	Frequency    string         `json:"frequency"`
	DayOfWeek    pgtype.Int2    `json:"day_of_week"`
	MaxStops     int32          `json:"max_stops"`
	PricePerStop pgtype.Numeric `json:"price_per_stop"`
	Currency     string         `json:"currency"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.ProviderID,
		arg.Name,
		arg.Description,
		arg.Postcodes,
		arg.Frequency,
		arg.DayOfWeek,
		arg.MaxStops,
		arg.PricePerStop,
		arg.Currency,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.Postcodes,
		&i.Frequency,
		&i.DayOfWeek,
		&i.MaxStops,
		&i.CurrentStops,
		&i.PricePerStop,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("provider_id", arg.ProviderID.String()).Msg("failed to create route")
		return i, err
	}
	return i, nil
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, provider_id, name, description, postcodes, frequency, day_of_week, max_stops, current_stops, price_per_stop, currency, is_active, created_at, updated_at FROM routes WHERE id = $1
`

func (q *Queries) GetRouteByIDQuery(ctx context.Context, id uuid.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.Postcodes,
		&i.Frequency,
		&i.DayOfWeek,
		&i.MaxStops,
		&i.CurrentStops,
		&i.PricePerStop,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("route_id", id.String()).Msg("route not found")
			return i, err
		}
		log.Error().Err(err).Str("route_id", id.String()).Msg("failed to get route by id")
		return i, err
	}
	return i, nil
}

const listRoutesByProvider = `-- name: ListRoutesByProvider :many
SELECT id, provider_id, name, description, postcodes, frequency, day_of_week, max_stops, current_stops, price_per_stop, currency, is_active, created_at, updated_at FROM routes WHERE provider_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRoutesByProviderQuery(ctx context.Context, providerID uuid.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByProvider, providerID)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to list routes by provider")
		return nil, err
	}
	defer rows.Close()

	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Description,
			&i.Postcodes,
			&i.Frequency,
			&i.DayOfWeek,
			&i.MaxStops,
			&i.CurrentStops,
			&i.PricePerStop,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan route row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes SET name = $2, description = $3, is_active = $4 WHERE id = $1
RETURNING id, provider_id, name, description, postcodes, frequency, day_of_week, max_stops, current_stops, price_per_stop, currency, is_active, created_at, updated_at
`

type UpdateRouteParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.Postcodes,
		&i.Frequency,
		&i.DayOfWeek,
		&i.MaxStops,
		&i.CurrentStops,
		&i.PricePerStop,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("route_id", arg.ID.String()).Msg("failed to update route")
		return i, err
	}
	return i, nil
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	if err != nil {
		log.Error().Err(err).Str("route_id", id.String()).Msg("failed to delete route")
		return err
	}
	return nil
}

const createRouteStop = `-- name: CreateRouteStop :one
INSERT INTO route_stops (route_id, customer_id, address, location, stop_order, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, route_id, customer_id, address, location, stop_order, notes, is_active, created_at
`

type CreateRouteStopParams struct {
	RouteID    uuid.UUID   `json:"route_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	Address    string      `json:"address"`
	Location   pgtype.Text `json:"location"`
	StopOrder  int32       `json:"stop_order"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateRouteStop(ctx context.Context, arg CreateRouteStopParams) (RouteStop, error) {
	row := q.db.QueryRow(ctx, createRouteStop,
		arg.RouteID,
		arg.CustomerID,
		arg.Address,
		arg.Location,
		arg.StopOrder,
		arg.Notes,
	)
	var i RouteStop
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.CustomerID,
		&i.Address,
		&i.Location,
		&i.StopOrder,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("route_id", arg.RouteID.String()).Msg("failed to create route stop")
		return i, err
	}
	return i, nil
}

const listStopsByRoute = `-- name: ListStopsByRoute :many
SELECT id, route_id, customer_id, address, location, stop_order, notes, is_active, created_at FROM route_stops WHERE route_id = $1 ORDER BY stop_order
`

func (q *Queries) ListStopsByRouteQuery(ctx context.Context, routeID uuid.UUID) ([]RouteStop, error) {
	rows, err := q.db.Query(ctx, listStopsByRoute, routeID)
	if err != nil {
		log.Error().Err(err).Str("route_id", routeID.String()).Msg("failed to list stops by route")
		return nil, err
	}
	defer rows.Close()

	items := []RouteStop{}
	for rows.Next() {
		var i RouteStop
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.CustomerID,
			&i.Address,
			&i.Location,
			&i.StopOrder,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan route stop row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRouteStop = `-- name: DeleteRouteStop :exec
DELETE FROM route_stops WHERE id = $1 AND route_id = $2
`

func (q *Queries) DeleteRouteStop(ctx context.Context, id uuid.UUID, routeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRouteStop, id, routeID)
	if err != nil {
		log.Error().Err(err).Str("stop_id", id.String()).Msg("failed to delete route stop")
		return err
	}
	return nil
}

const updateRouteStopOrder = `-- name: UpdateRouteStopOrder :exec
UPDATE route_stops SET stop_order = $2 WHERE id = $1
`

func (q *Queries) UpdateRouteStopOrder(ctx context.Context, id uuid.UUID, stopOrder int32) error {
	_, err := q.db.Exec(ctx, updateRouteStopOrder, id, stopOrder)
	if err != nil {
		log.Error().Err(err).Str("stop_id", id.String()).Msg("failed to update route stop order")
		return err
	}
	return nil
}
