// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

// --- Enum types for safety ---

type SOSStatus string

const (
	SOSStatusActive     SOSStatus = "active"
	SOSStatusResponded  SOSStatus = "responded"
	SOSStatusResolved   SOSStatus = "resolved"
	SOSStatusFalseAlarm SOSStatus = "false_alarm"
)

// --- Table models ---

type SOSAlert struct {
	ID                        uuid.UUID          `json:"id"`
	UserID                    uuid.UUID          `json:"user_id"`
	JobID                     *uuid.UUID         `json:"job_id"`
	Latitude                  float64            `json:"latitude"`
	Longitude                 float64            `json:"longitude"`
	Status                    SOSStatus          `json:"status"`
	EmergencyContactsNotified bool               `json:"emergency_contacts_notified"`
	Notes                     pgtype.Text        `json:"notes"`
	CreatedAt                 time.Time          `json:"created_at"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
}

type LocationShare struct {
	ID        uuid.UUID    `json:"id"`
	JobID     uuid.UUID    `json:"job_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Latitude  float64      `json:"latitude"`
	Longitude float64      `json:"longitude"`
	Accuracy  pgtype.Float4 `json:"accuracy"`
	SharedAt  time.Time    `json:"shared_at"`
}

type EmergencyContact struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	Relationship pgtype.Text `json:"relationship"`
	CreatedAt    time.Time   `json:"created_at"`
}

// --- Query implementations ---

const createSOSAlert = `-- name: CreateSOSAlert :one
INSERT INTO sos_alerts (user_id, job_id, latitude, longitude, status, emergency_contacts_notified, notes)
VALUES ($1, $2, $3, $4, 'active', $5, $6)
RETURNING id, user_id, job_id, latitude, longitude, status, emergency_contacts_notified, notes, created_at, resolved_at
`

type CreateSOSAlertParams struct {
	UserID                    uuid.UUID   `json:"user_id"`
	JobID                     *uuid.UUID  `json:"job_id"`
	Latitude                  float64     `json:"latitude"`
	Longitude                 float64     `json:"longitude"`
	EmergencyContactsNotified bool        `json:"emergency_contacts_notified"`
	Notes                     pgtype.Text `json:"notes"`
}

func (q *Queries) CreateSOSAlert(ctx context.Context, arg CreateSOSAlertParams) (SOSAlert, error) {
	row := q.db.QueryRow(ctx, createSOSAlert,
		arg.UserID,
		arg.JobID,
		arg.Latitude,
		arg.Longitude,
		arg.EmergencyContactsNotified,
		arg.Notes,
	)
	var i SOSAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.EmergencyContactsNotified,
		&i.Notes,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to create SOS alert")
		return i, err
	}
	return i, nil
}

const getSOSAlert = `-- name: GetSOSAlert :one
SELECT id, user_id, job_id, latitude, longitude, status, emergency_contacts_notified, notes, created_at, resolved_at FROM sos_alerts WHERE id = $1
`

func (q *Queries) GetSOSAlert(ctx context.Context, id uuid.UUID) (SOSAlert, error) {
	row := q.db.QueryRow(ctx, getSOSAlert, id)
	var i SOSAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.EmergencyContactsNotified,
		&i.Notes,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("alert_id", id.String()).Msg("SOS alert not found")
			return i, err
		}
		log.Error().Err(err).Str("alert_id", id.String()).Msg("failed to get SOS alert")
		return i, err
	}
	return i, nil
}

const resolveSOSAlert = `-- name: ResolveSOSAlert :one
UPDATE sos_alerts
SET status = $2, resolved_at = NOW(), notes = COALESCE($3, notes)
WHERE id = $1
RETURNING id, user_id, job_id, latitude, longitude, status, emergency_contacts_notified, notes, created_at, resolved_at
`

func (q *Queries) ResolveSOSAlert(ctx context.Context, id uuid.UUID, status SOSStatus, notes pgtype.Text) (SOSAlert, error) {
	row := q.db.QueryRow(ctx, resolveSOSAlert, id, status, notes)
	var i SOSAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.EmergencyContactsNotified,
		&i.Notes,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("alert_id", id.String()).Msg("failed to resolve SOS alert")
		return i, err
	}
	return i, nil
}

const listActiveSOSAlerts = `-- name: ListActiveSOSAlerts :many
SELECT sa.id, sa.user_id, sa.job_id, sa.latitude, sa.longitude, sa.status, sa.emergency_contacts_notified, sa.notes, sa.created_at, sa.resolved_at,
       u.name as user_name, u.phone as user_phone
FROM sos_alerts sa
JOIN users u ON u.id = sa.user_id
WHERE sa.status = 'active'
ORDER BY sa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveSOSAlertsRow struct {
	ID                        uuid.UUID          `json:"id"`
	UserID                    uuid.UUID          `json:"user_id"`
	JobID                     *uuid.UUID         `json:"job_id"`
	Latitude                  float64            `json:"latitude"`
	Longitude                 float64            `json:"longitude"`
	Status                    SOSStatus          `json:"status"`
	EmergencyContactsNotified bool               `json:"emergency_contacts_notified"`
	Notes                     pgtype.Text        `json:"notes"`
	CreatedAt                 time.Time          `json:"created_at"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	UserName                  pgtype.Text        `json:"user_name"`
	UserPhone                 string             `json:"user_phone"`
}

func (q *Queries) ListActiveSOSAlerts(ctx context.Context, limit int32, offset int32) ([]ListActiveSOSAlertsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSOSAlerts, limit, offset)
	if err != nil {
		log.Error().Err(err).Msg("failed to list active SOS alerts")
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSOSAlertsRow{}
	for rows.Next() {
		var i ListActiveSOSAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.EmergencyContactsNotified,
			&i.Notes,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UserName,
			&i.UserPhone,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan active SOS alert row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating active SOS alert rows")
		return nil, err
	}
	return items, nil
}

const listSOSAlertsByUser = `-- name: ListSOSAlertsByUser :many
SELECT id, user_id, job_id, latitude, longitude, status, emergency_contacts_notified, notes, created_at, resolved_at FROM sos_alerts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListSOSAlertsByUser(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]SOSAlert, error) {
	rows, err := q.db.Query(ctx, listSOSAlertsByUser, userID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to list SOS alerts by user")
		return nil, err
	}
	defer rows.Close()
	items := []SOSAlert{}
	for rows.Next() {
		var i SOSAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.EmergencyContactsNotified,
			&i.Notes,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan SOS alert row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating SOS alert rows")
		return nil, err
	}
	return items, nil
}

const shareLocation = `-- name: ShareLocation :one
INSERT INTO location_shares (job_id, user_id, latitude, longitude, accuracy)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, user_id, latitude, longitude, accuracy, shared_at
`

type ShareLocationParams struct {
	JobID     uuid.UUID     `json:"job_id"`
	UserID    uuid.UUID     `json:"user_id"`
	Latitude  float64       `json:"latitude"`
	Longitude float64       `json:"longitude"`
	Accuracy  pgtype.Float4 `json:"accuracy"`
}

func (q *Queries) ShareLocation(ctx context.Context, arg ShareLocationParams) (LocationShare, error) {
	row := q.db.QueryRow(ctx, shareLocation,
		arg.JobID,
		arg.UserID,
		arg.Latitude,
		arg.Longitude,
		arg.Accuracy,
	)
	var i LocationShare
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Accuracy,
		&i.SharedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to share location")
		return i, err
	}
	return i, nil
}

const getLatestLocation = `-- name: GetLatestLocation :one
SELECT id, job_id, user_id, latitude, longitude, accuracy, shared_at FROM location_shares
WHERE job_id = $1 AND user_id = $2
ORDER BY shared_at DESC
LIMIT 1
`

func (q *Queries) GetLatestLocation(ctx context.Context, jobID uuid.UUID, userID uuid.UUID) (LocationShare, error) {
	row := q.db.QueryRow(ctx, getLatestLocation, jobID, userID)
	var i LocationShare
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Accuracy,
		&i.SharedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("job_id", jobID.String()).Msg("no location data found")
			return i, err
		}
		log.Error().Err(err).Str("job_id", jobID.String()).Msg("failed to get latest location")
		return i, err
	}
	return i, nil
}

const getLocationHistory = `-- name: GetLocationHistory :many
SELECT id, job_id, user_id, latitude, longitude, accuracy, shared_at FROM location_shares
WHERE job_id = $1
ORDER BY shared_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) GetLocationHistory(ctx context.Context, jobID uuid.UUID, limit int32, offset int32) ([]LocationShare, error) {
	rows, err := q.db.Query(ctx, getLocationHistory, jobID, limit, offset)
	if err != nil {
		log.Error().Err(err).Str("job_id", jobID.String()).Msg("failed to get location history")
		return nil, err
	}
	defer rows.Close()
	items := []LocationShare{}
	for rows.Next() {
		var i LocationShare
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.Latitude,
			&i.Longitude,
			&i.Accuracy,
			&i.SharedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan location share row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating location share rows")
		return nil, err
	}
	return items, nil
}

const addEmergencyContact = `-- name: AddEmergencyContact :one
INSERT INTO emergency_contacts (user_id, name, phone, relationship)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, phone, relationship, created_at
`

type AddEmergencyContactParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	Relationship pgtype.Text `json:"relationship"`
}

func (q *Queries) AddEmergencyContact(ctx context.Context, arg AddEmergencyContactParams) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, addEmergencyContact,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Relationship,
	)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.UserID.String()).Msg("failed to add emergency contact")
		return i, err
	}
	return i, nil
}

const listEmergencyContacts = `-- name: ListEmergencyContacts :many
SELECT id, user_id, name, phone, relationship, created_at FROM emergency_contacts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEmergencyContacts(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error) {
	rows, err := q.db.Query(ctx, listEmergencyContacts, userID)
	if err != nil {
		log.Error().Err(err).Str("user_id", userID.String()).Msg("failed to list emergency contacts")
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Relationship,
			&i.CreatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan emergency contact row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating emergency contact rows")
		return nil, err
	}
	return items, nil
}

const removeEmergencyContact = `-- name: RemoveEmergencyContact :exec
DELETE FROM emergency_contacts WHERE id = $1 AND user_id = $2
`

func (q *Queries) RemoveEmergencyContact(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeEmergencyContact, id, userID)
	if err != nil {
		log.Error().Err(err).Str("contact_id", id.String()).Msg("failed to remove emergency contact")
	}
	return err
}

const getEmergencyContact = `-- name: GetEmergencyContact :one
SELECT id, user_id, name, phone, relationship, created_at FROM emergency_contacts WHERE id = $1
`

func (q *Queries) GetEmergencyContact(ctx context.Context, id uuid.UUID) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, getEmergencyContact, id)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("contact_id", id.String()).Msg("emergency contact not found")
			return i, err
		}
		log.Error().Err(err).Str("contact_id", id.String()).Msg("failed to get emergency contact")
		return i, err
	}
	return i, nil
}
