// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_gateway, gateway_order_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at
`

type CreateTransactionParams struct {
	JobID                uuid.UUID      `json:"job_id"`
	Amount               pgtype.Numeric `json:"amount"`
	Currency             string         `json:"currency"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	CommissionAmount     pgtype.Numeric `json:"commission_amount"`
	TaxAmount            pgtype.Numeric `json:"tax_amount"`
	ProviderPayoutAmount pgtype.Numeric `json:"provider_payout_amount"`
	PaymentGateway       pgtype.Text    `json:"payment_gateway"`
	GatewayOrderID       pgtype.Text    `json:"gateway_order_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.JobID,
		arg.Amount,
		arg.Currency,
		arg.CommissionRate,
		arg.CommissionAmount,
		arg.TaxAmount,
		arg.ProviderPayoutAmount,
		arg.PaymentGateway,
		arg.GatewayOrderID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("job_id", arg.JobID.String()).Msg("failed to create transaction")
		return i, err
	}
	return i, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("transaction_id", id.String()).Msg("transaction not found")
			return i, err
		}
		log.Error().Err(err).Str("transaction_id", id.String()).Msg("failed to get transaction by id")
		return i, err
	}
	return i, nil
}

const getTransactionByJob = `-- name: GetTransactionByJob :one
SELECT id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at FROM transactions WHERE job_id = $1
`

func (q *Queries) GetTransactionByJob(ctx context.Context, jobID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByJob, jobID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("job_id", jobID.String()).Msg("transaction not found for job")
			return i, err
		}
		log.Error().Err(err).Str("job_id", jobID.String()).Msg("failed to get transaction by job")
		return i, err
	}
	return i, nil
}

const getTransactionByGatewayOrder = `-- name: GetTransactionByGatewayOrder :one
SELECT id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at FROM transactions WHERE gateway_order_id = $1
`

func (q *Queries) GetTransactionByGatewayOrder(ctx context.Context, gatewayOrderID string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByGatewayOrder, gatewayOrderID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("gateway_order_id", gatewayOrderID).Msg("transaction not found by gateway order")
			return i, err
		}
		log.Error().Err(err).Str("gateway_order_id", gatewayOrderID).Msg("failed to get transaction by gateway order")
		return i, err
	}
	return i, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE transactions
SET payment_status = $2,
    gateway_payment_id = $3,
    gateway_signature = $4,
    paid_at = CASE WHEN $2 = 'captured' THEN NOW() ELSE paid_at END
WHERE id = $1
RETURNING id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID               uuid.UUID     `json:"id"`
	PaymentStatus    PaymentStatus `json:"payment_status"`
	GatewayPaymentID pgtype.Text   `json:"gateway_payment_id"`
	GatewaySignature pgtype.Text   `json:"gateway_signature"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.PaymentStatus,
		arg.GatewayPaymentID,
		arg.GatewaySignature,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("transaction_id", arg.ID.String()).Msg("failed to update payment status")
		return i, err
	}
	return i, nil
}

const releaseEscrow = `-- name: ReleaseEscrow :one
UPDATE transactions
SET escrow_status = 'released',
    settled_at = NOW()
WHERE id = $1
RETURNING id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at
`

func (q *Queries) ReleaseEscrow(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, releaseEscrow, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("transaction_id", id.String()).Msg("failed to release escrow")
		return i, err
	}
	return i, nil
}

const refundTransaction = `-- name: RefundTransaction :one
UPDATE transactions
SET payment_status = 'refunded',
    refund_amount = $2,
    refunded_at = NOW(),
    escrow_status = 'refunded'
WHERE id = $1
RETURNING id, job_id, amount, currency, commission_rate, commission_amount, tax_amount, provider_payout_amount, payment_status, escrow_status, payment_gateway, gateway_order_id, gateway_payment_id, gateway_signature, paid_at, settled_at, refund_amount, refunded_at, metadata, created_at, updated_at
`

type RefundTransactionParams struct {
	ID           uuid.UUID      `json:"id"`
	RefundAmount pgtype.Numeric `json:"refund_amount"`
}

func (q *Queries) RefundTransaction(ctx context.Context, arg RefundTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, refundTransaction, arg.ID, arg.RefundAmount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Amount,
		&i.Currency,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.TaxAmount,
		&i.ProviderPayoutAmount,
		&i.PaymentStatus,
		&i.EscrowStatus,
		&i.PaymentGateway,
		&i.GatewayOrderID,
		&i.GatewayPaymentID,
		&i.GatewaySignature,
		&i.PaidAt,
		&i.SettledAt,
		&i.RefundAmount,
		&i.RefundedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("transaction_id", arg.ID.String()).Msg("failed to refund transaction")
		return i, err
	}
	return i, nil
}

const listUnsettledTransactions = `-- name: ListUnsettledTransactions :many
SELECT t.id, t.job_id, t.amount, t.currency, t.commission_rate, t.commission_amount, t.tax_amount, t.provider_payout_amount, t.payment_status, t.escrow_status, t.payment_gateway, t.gateway_order_id, t.gateway_payment_id, t.gateway_signature, t.paid_at, t.settled_at, t.refund_amount, t.refunded_at, t.metadata, t.created_at, t.updated_at,
       j.provider_id
FROM transactions t
JOIN jobs j ON j.id = t.job_id
WHERE t.payment_status = 'captured'
  AND t.escrow_status = 'held'
  AND t.paid_at < NOW() - INTERVAL '24 hours'
ORDER BY t.paid_at ASC
LIMIT $1
`

type ListUnsettledTransactionsRow struct {
	Transaction
	ProviderID *uuid.UUID `json:"provider_id"`
}

func (q *Queries) ListUnsettledTransactions(ctx context.Context, limit int32) ([]ListUnsettledTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listUnsettledTransactions, limit)
	if err != nil {
		log.Error().Err(err).Msg("failed to list unsettled transactions")
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsettledTransactionsRow{}
	for rows.Next() {
		var i ListUnsettledTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Amount,
			&i.Currency,
			&i.CommissionRate,
			&i.CommissionAmount,
			&i.TaxAmount,
			&i.ProviderPayoutAmount,
			&i.PaymentStatus,
			&i.EscrowStatus,
			&i.PaymentGateway,
			&i.GatewayOrderID,
			&i.GatewayPaymentID,
			&i.GatewaySignature,
			&i.PaidAt,
			&i.SettledAt,
			&i.RefundAmount,
			&i.RefundedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan unsettled transaction row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating unsettled transaction rows")
		return nil, err
	}
	return items, nil
}

const getProviderEarnings = `-- name: GetProviderEarnings :one
SELECT
    COALESCE(SUM(provider_payout_amount), 0) as total_earnings,
    COUNT(*) as total_transactions
FROM transactions t
JOIN jobs j ON j.id = t.job_id
WHERE j.provider_id = $1
  AND t.payment_status = 'captured'
  AND t.settled_at IS NOT NULL
`

type GetProviderEarningsRow struct {
	TotalEarnings      pgtype.Numeric `json:"total_earnings"`
	TotalTransactions  int64          `json:"total_transactions"`
}

func (q *Queries) GetProviderEarnings(ctx context.Context, providerID uuid.UUID) (GetProviderEarningsRow, error) {
	row := q.db.QueryRow(ctx, getProviderEarnings, providerID)
	var i GetProviderEarningsRow
	err := row.Scan(&i.TotalEarnings, &i.TotalTransactions)
	if err != nil {
		log.Error().Err(err).Str("provider_id", providerID.String()).Msg("failed to get provider earnings")
		return i, err
	}
	return i, nil
}
