// Code generated by seva-codegen. DO NOT EDIT.

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (type, phone, email, name, jurisdiction_id, preferred_language, device_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, phone, email, name, avatar_url, jurisdiction_id, preferred_language, device_type, is_active, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	Type              UserType    `json:"type"`
	Phone             string      `json:"phone"`
	Email             pgtype.Text `json:"email"`
	Name              pgtype.Text `json:"name"`
	JurisdictionID    string      `json:"jurisdiction_id"`
	PreferredLanguage string      `json:"preferred_language"`
	DeviceType        DeviceType  `json:"device_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Type,
		arg.Phone,
		arg.Email,
		arg.Name,
		arg.JurisdictionID,
		arg.PreferredLanguage,
		arg.DeviceType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.JurisdictionID,
		&i.PreferredLanguage,
		&i.DeviceType,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Msg("failed to create user")
		return i, err
	}
	return i, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, type, phone, email, name, avatar_url, jurisdiction_id, preferred_language, device_type, is_active, last_seen_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.JurisdictionID,
		&i.PreferredLanguage,
		&i.DeviceType,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("user_id", id.String()).Msg("user not found")
			return i, err
		}
		log.Error().Err(err).Str("user_id", id.String()).Msg("failed to get user by id")
		return i, err
	}
	return i, nil
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, type, phone, email, name, avatar_url, jurisdiction_id, preferred_language, device_type, is_active, last_seen_at, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.JurisdictionID,
		&i.PreferredLanguage,
		&i.DeviceType,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			log.Debug().Str("phone", phone).Msg("user not found by phone")
			return i, err
		}
		log.Error().Err(err).Str("phone", phone).Msg("failed to get user by phone")
		return i, err
	}
	return i, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($2, name),
    email = COALESCE($3, email),
    avatar_url = COALESCE($4, avatar_url),
    preferred_language = COALESCE($5, preferred_language),
    device_type = COALESCE($6, device_type)
WHERE id = $1
RETURNING id, type, phone, email, name, avatar_url, jurisdiction_id, preferred_language, device_type, is_active, last_seen_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              pgtype.Text `json:"name"`
	Email             pgtype.Text `json:"email"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	PreferredLanguage pgtype.Text `json:"preferred_language"`
	DeviceType        pgtype.Text `json:"device_type"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.PreferredLanguage,
		arg.DeviceType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.JurisdictionID,
		&i.PreferredLanguage,
		&i.DeviceType,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		log.Error().Err(err).Str("user_id", arg.ID.String()).Msg("failed to update user")
		return i, err
	}
	return i, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	if err != nil {
		log.Error().Err(err).Str("user_id", id.String()).Msg("failed to update last seen")
	}
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	if err != nil {
		log.Error().Err(err).Str("user_id", id.String()).Msg("failed to deactivate user")
	}
	return err
}

const listUsersByJurisdiction = `-- name: ListUsersByJurisdiction :many
SELECT id, type, phone, email, name, avatar_url, jurisdiction_id, preferred_language, device_type, is_active, last_seen_at, created_at, updated_at FROM users
WHERE jurisdiction_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByJurisdictionParams struct {
	JurisdictionID string `json:"jurisdiction_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListUsersByJurisdiction(ctx context.Context, arg ListUsersByJurisdictionParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByJurisdiction,
		arg.JurisdictionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		log.Error().Err(err).Str("jurisdiction_id", arg.JurisdictionID).Msg("failed to list users by jurisdiction")
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Phone,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.JurisdictionID,
			&i.PreferredLanguage,
			&i.DeviceType,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			log.Error().Err(err).Msg("failed to scan user row")
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		log.Error().Err(err).Msg("error iterating user rows")
		return nil, err
	}
	return items, nil
}

const countUsersByType = `-- name: CountUsersByType :one
SELECT COUNT(*) FROM users WHERE type = $1 AND is_active = true
`

func (q *Queries) CountUsersByType(ctx context.Context, userType UserType) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByType, userType)
	var count int64
	err := row.Scan(&count)
	if err != nil {
		log.Error().Err(err).Str("user_type", string(userType)).Msg("failed to count users by type")
		return 0, err
	}
	return count, nil
}
