package main

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"github.com/rs/zerolog/log"

	"github.com/seva-platform/backend/internal/adapter/sms"
	"github.com/seva-platform/backend/internal/config"
	"github.com/seva-platform/backend/internal/handler"
	"github.com/seva-platform/backend/internal/middleware"
	"github.com/seva-platform/backend/internal/worker"
	"github.com/seva-platform/backend/pkg/logger"
)

func main() {
	// ---- Configuration ----
	cfg, err := config.Load()
	if err != nil {
		log.Fatal().Err(err).Msg("failed to load configuration")
	}

	// ---- Logger ----
	logger.Setup(cfg.Environment)
	log.Info().Str("env", cfg.Environment).Msg("starting Seva API")

	// ---- PostgreSQL ----
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	dbPool, err := pgxpool.New(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to create database pool")
	}
	defer dbPool.Close()

	if err := dbPool.Ping(ctx); err != nil {
		log.Fatal().Err(err).Msg("failed to ping database")
	}
	log.Info().Msg("connected to PostgreSQL")

	// ---- Redis ----
	redisOpts, err := parseRedisURL(cfg.RedisURL)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to parse Redis URL")
	}
	rdb := redis.NewClient(redisOpts)
	defer rdb.Close()

	if err := rdb.Ping(ctx).Err(); err != nil {
		log.Fatal().Err(err).Msg("failed to ping Redis")
	}
	log.Info().Msg("connected to Redis")

	// ---- SMS Adapter ----
	smsProvider, err := sms.NewSMSProvider(cfg.SMSProvider, cfg.SMSAPIKey)
	if err != nil {
		log.Warn().Err(err).Msg("SMS provider not configured, falling back to noop")
		smsProvider = &sms.NoopProvider{}
	}

	// ---- Repositories ----
	// TODO: Wire up real repository implementations once generated by sqlc.
	// userRepo     := postgres.NewUserRepository(dbPool)
	// providerRepo := postgres.NewProviderRepository(dbPool)
	// jobRepo      := postgres.NewJobRepository(dbPool)
	// categoryRepo := postgres.NewCategoryRepository(dbPool)
	// cacheStore   := redis.NewCacheStore(rdb)
	// sessionStore := redis.NewSessionStore(rdb)

	// ---- Services ----
	// TODO: Wire up real service implementations with their repository dependencies.
	// userSvc         := service.NewUserService(userRepo, cacheStore)
	// providerSvc     := service.NewProviderService(providerRepo, userRepo, cacheStore)
	// jobSvc          := service.NewJobService(jobRepo, userRepo, providerRepo)
	// searchSvc       := service.NewSearchService(providerRepo, jobRepo, categoryRepo, cacheStore)
	// paymentSvc      := service.NewPaymentService(paymentGateway, jobRepo, userRepo)
	// reviewSvc       := service.NewReviewService(reviewRepo, jobRepo, providerRepo)
	// disputeSvc      := service.NewDisputeService(disputeRepo, jobRepo, userRepo)
	// adminSvc        := service.NewAdminService(userRepo, jobRepo, providerRepo, categoryRepo)
	// gamificationSvc := service.NewGamificationService(pointsRepo, userRepo)
	// routeSvc        := service.NewRouteService(routeRepo, providerRepo)
	// notifSvc        := service.NewNotificationService(notifRepo, userRepo)
	// aiSvc           := service.NewAIService(categoryRepo, jobRepo)

	// ---- Handlers ----
	healthHandler := handler.NewHealthHandler(dbPool, rdb)
	authHandler := handler.NewAuthHandler(cfg, nil, smsProvider)

	// The following handlers require service implementations.
	// Once the services above are wired, replace nil with the real service.
	var (
		userHandler         *handler.UserHandler
		jobHandler          *handler.JobHandler
		providerHandler     *handler.ProviderHandler
		searchHandler       *handler.SearchHandler
		paymentHandler      *handler.PaymentHandler
		reviewHandler       *handler.ReviewHandler
		disputeHandler      *handler.DisputeHandler
		adminHandler        *handler.AdminHandler
		gamificationHandler *handler.GamificationHandler
		routeHandler        *handler.RouteHandler
		notificationHandler *handler.NotificationHandler
		aiHandler           *handler.AIHandler
	)

	// TODO: Uncomment and wire once service layer is implemented:
	// userHandler         = handler.NewUserHandler(userSvc)
	// jobHandler          = handler.NewJobHandler(jobSvc)
	// providerHandler     = handler.NewProviderHandler(providerSvc)
	// searchHandler       = handler.NewSearchHandler(searchSvc)
	// paymentHandler      = handler.NewPaymentHandler(paymentSvc)
	// reviewHandler       = handler.NewReviewHandler(reviewSvc)
	// disputeHandler      = handler.NewDisputeHandler(disputeSvc)
	// adminHandler        = handler.NewAdminHandler(adminSvc)
	// gamificationHandler = handler.NewGamificationHandler(gamificationSvc)
	// routeHandler        = handler.NewRouteHandler(routeSvc)
	// notificationHandler = handler.NewNotificationHandler(notifSvc)
	// aiHandler           = handler.NewAIHandler(aiSvc)

	// Prevent unused variable warnings until services are wired.
	_ = userHandler
	_ = jobHandler
	_ = providerHandler
	_ = searchHandler
	_ = paymentHandler
	_ = reviewHandler
	_ = disputeHandler
	_ = adminHandler
	_ = gamificationHandler
	_ = routeHandler
	_ = notificationHandler
	_ = aiHandler

	// ---- Asynq Worker ----
	w := worker.NewWorker(redisOpts.Addr, &worker.Deps{})
	go func() {
		if err := w.Start(); err != nil {
			log.Error().Err(err).Msg("asynq worker stopped with error")
		}
	}()

	// ---- Fiber App ----
	app := fiber.New(fiber.Config{
		AppName:               "Seva API",
		ReadTimeout:           15 * time.Second,
		WriteTimeout:          15 * time.Second,
		IdleTimeout:           60 * time.Second,
		BodyLimit:             15 * 1024 * 1024, // 15MB for file uploads
		DisableStartupMessage: cfg.IsProd(),
		ErrorHandler:          customErrorHandler,
	})

	// ---- Global Middleware ----
	app.Use(recover.New())
	app.Use(requestid.New())
	app.Use(logger.FiberLogger())
	app.Use(middleware.NewCORS(cfg))
	app.Use(limiter.New(limiter.Config{
		Max:        cfg.RateLimitMax(),
		Expiration: 1 * time.Second,
	}))

	// ---- Route Groups ----
	api := app.Group("/api/v1")

	// --- Public Routes ---

	// Health (public)
	healthHandler.RegisterRoutes(api.Group("/health"))

	// Auth (public)
	authHandler.RegisterRoutes(api.Group("/auth"))

	// Search (public)
	if searchHandler != nil {
		searchHandler.RegisterSearchRoutes(api.Group("/search"))
	}

	// Categories (public)
	if searchHandler != nil {
		searchHandler.RegisterCategoryRoutes(api.Group("/categories"))
	}

	// --- Authenticated Routes ---
	jwtMiddleware := middleware.NewJWTAuth(cfg)

	// Users
	if userHandler != nil {
		userHandler.RegisterRoutes(api.Group("/users", jwtMiddleware))
	}

	// Jobs
	if jobHandler != nil {
		jobHandler.RegisterRoutes(api.Group("/jobs", jwtMiddleware))
	}

	// Providers
	if providerHandler != nil {
		providerHandler.RegisterRoutes(api.Group("/providers", jwtMiddleware))
	}

	// Reviews
	if reviewHandler != nil {
		reviewHandler.RegisterRoutes(api.Group("/reviews", jwtMiddleware))
		// Provider review and rating sub-routes are registered on the providers group.
		reviewHandler.RegisterProviderReviewRoutes(api.Group("/providers", jwtMiddleware))
	}

	// Payments
	if paymentHandler != nil {
		paymentHandler.RegisterRoutes(api.Group("/payments", jwtMiddleware))
	}

	// Disputes
	if disputeHandler != nil {
		disputeHandler.RegisterRoutes(api.Group("/disputes", jwtMiddleware))
	}

	// Points / Gamification
	if gamificationHandler != nil {
		gamificationHandler.RegisterRoutes(api.Group("/points", jwtMiddleware))
	}

	// Routes (service worker route management)
	if routeHandler != nil {
		routeHandler.RegisterRoutes(api.Group("/routes", jwtMiddleware))
	}

	// Notifications
	if notificationHandler != nil {
		notificationHandler.RegisterRoutes(api.Group("/notifications", jwtMiddleware))
	}

	// AI endpoints (authenticated)
	if aiHandler != nil {
		aiHandler.RegisterRoutes(api.Group("/ai", jwtMiddleware))
	}

	// --- Admin Routes (admin role required) ---
	adminGroup := api.Group("/admin", jwtMiddleware, middleware.RequireAdmin())
	if adminHandler != nil {
		adminHandler.RegisterRoutes(adminGroup)
	}
	if disputeHandler != nil {
		disputeHandler.RegisterAdminRoutes(adminGroup.Group("/disputes"))
	}

	// --- Webhook Routes (signature-verified, no JWT) ---
	webhookGroup := app.Group("/webhooks")
	if paymentHandler != nil {
		paymentHandler.RegisterWebhookRoutes(webhookGroup)
	}

	// ---- Graceful Shutdown ----
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		addr := fmt.Sprintf(":%s", cfg.ServerPort)
		if err := app.Listen(addr); err != nil {
			log.Fatal().Err(err).Msg("server failed to start")
		}
	}()

	<-quit
	log.Info().Msg("shutting down gracefully...")

	w.Shutdown()

	if err := app.ShutdownWithTimeout(30 * time.Second); err != nil {
		log.Error().Err(err).Msg("error during server shutdown")
	}

	log.Info().Msg("server stopped")
}

// parseRedisURL converts a redis:// URL into go-redis options.
func parseRedisURL(rawURL string) (*redis.Options, error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return nil, fmt.Errorf("invalid redis URL: %w", err)
	}

	addr := u.Host
	if u.Port() == "" {
		addr = u.Host + ":6379"
	}

	password, _ := u.User.Password()

	db := 0
	if len(u.Path) > 1 {
		fmt.Sscanf(u.Path[1:], "%d", &db)
	}

	return &redis.Options{
		Addr:     addr,
		Password: password,
		DB:       db,
	}, nil
}

// customErrorHandler returns consistent JSON error responses.
func customErrorHandler(c *fiber.Ctx, err error) error {
	code := fiber.StatusInternalServerError
	message := "internal server error"

	if e, ok := err.(*fiber.Error); ok {
		code = e.Code
		message = e.Message
	}

	log.Error().Err(err).Int("status", code).Str("path", c.Path()).Msg("request error")

	return c.Status(code).JSON(fiber.Map{
		"error": fiber.Map{
			"code":    code,
			"message": message,
		},
	})
}
